import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "adapters/index": "src/adapters/index.ts",
    "adapters/dispatcher-sse": "src/adapters/dispatcher-sse.ts",
    "adapters/mcp-catalog": "src/adapters/mcp-catalog.ts",
    "adapters/prisma-rollout": "src/adapters/prisma-rollout.ts",
    commands: "src/commands.ts",
    cli: "src/cli.ts",
    definitions: "src/definitions.ts",
    dispatcher: "src/dispatcher.ts",
    "durable-turn": "src/durable-turn.ts",
    "hook-pipeline": "src/hook-pipeline.ts",
    loop: "src/loop.ts",
    "mcp-bridge": "src/mcp-bridge.ts",
    model: "src/model.ts",
    orchestration: "src/orchestration.ts",
    policy: "src/policy.ts",
    protocol: "src/protocol.ts",
    pulsar: "src/pulsar.ts",
    rollout: "src/rollout.ts",
    "rollout-store-persistent": "src/rollout-store-persistent.ts",
    sandbox: "src/sandbox.ts",
    skills: "src/skills.ts",
    subagents: "src/subagents.ts",
    tools: "src/tools.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  target: "es2022",
  external: ["@nebutra/execution-policy", "@nebutra/mcp"],
});
