/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/misc/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns health status of the API gateway and its dependencies. Returns 200 for healthy/degraded, 503 for unhealthy.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is healthy or degraded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              version: string;
              uptime: number;
              timestamp: string;
              dependencies: {
                database: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
                cache: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
              };
            };
          };
        };
        /** @description Service is unhealthy — all dependencies are down */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              version: string;
              uptime: number;
              timestamp: string;
              dependencies: {
                database: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
                cache: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Comprehensive system status
     * @description Returns detailed status of all system components including database, Redis, and microservices. Used by OpenStatus monitoring.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description System is healthy or degraded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              timestamp: string;
              version: string;
              /** @enum {string} */
              database: "connected" | "disconnected";
              /** @enum {string} */
              redis: "connected" | "disconnected";
              services: {
                /** @enum {string} */
                ai: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                content: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                recsys: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                ecommerce: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                web3: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                billing: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                eventIngest: "available" | "unavailable" | "unknown";
              };
              uptime: number;
              checks: {
                name: string;
                /** @enum {string} */
                status: "pass" | "fail";
                latency?: number;
                message?: string;
              }[];
            };
          };
        };
        /** @description System is unhealthy */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              timestamp: string;
              version: string;
              /** @enum {string} */
              database: "connected" | "disconnected";
              /** @enum {string} */
              redis: "connected" | "disconnected";
              services: {
                /** @enum {string} */
                ai: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                content: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                recsys: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                ecommerce: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                web3: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                billing: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                eventIngest: "available" | "unavailable" | "unknown";
              };
              uptime: number;
              checks: {
                name: string;
                /** @enum {string} */
                status: "pass" | "fail";
                latency?: number;
                message?: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kubernetes readiness probe
     * @description Returns whether the service is ready to accept traffic
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is ready */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ready: true;
            };
          };
        };
        /** @description Service is not ready */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ready: false;
              reason: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kubernetes liveness probe
     * @description Returns whether the service process is alive
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is alive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              live: true;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Simple uptime ping
     * @description Returns 'pong' for uptime monitoring services
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description pong */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/misc/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns health status of the API gateway and its dependencies. Returns 200 for healthy/degraded, 503 for unhealthy.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is healthy or degraded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              version: string;
              uptime: number;
              timestamp: string;
              dependencies: {
                database: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
                cache: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
              };
            };
          };
        };
        /** @description Service is unhealthy — all dependencies are down */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              version: string;
              uptime: number;
              timestamp: string;
              dependencies: {
                database: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
                cache: {
                  /** @enum {string} */
                  status: "up" | "down";
                  latencyMs: number;
                };
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Comprehensive system status
     * @description Returns detailed status of all system components including database, Redis, and microservices. Used by OpenStatus monitoring.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description System is healthy or degraded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              timestamp: string;
              version: string;
              /** @enum {string} */
              database: "connected" | "disconnected";
              /** @enum {string} */
              redis: "connected" | "disconnected";
              services: {
                /** @enum {string} */
                ai: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                content: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                recsys: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                ecommerce: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                web3: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                billing: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                eventIngest: "available" | "unavailable" | "unknown";
              };
              uptime: number;
              checks: {
                name: string;
                /** @enum {string} */
                status: "pass" | "fail";
                latency?: number;
                message?: string;
              }[];
            };
          };
        };
        /** @description System is unhealthy */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy" | "degraded" | "unhealthy";
              timestamp: string;
              version: string;
              /** @enum {string} */
              database: "connected" | "disconnected";
              /** @enum {string} */
              redis: "connected" | "disconnected";
              services: {
                /** @enum {string} */
                ai: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                content: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                recsys: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                ecommerce: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                web3: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                billing: "available" | "unavailable" | "unknown";
                /** @enum {string} */
                eventIngest: "available" | "unavailable" | "unknown";
              };
              uptime: number;
              checks: {
                name: string;
                /** @enum {string} */
                status: "pass" | "fail";
                latency?: number;
                message?: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kubernetes readiness probe
     * @description Returns whether the service is ready to accept traffic
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is ready */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ready: true;
            };
          };
        };
        /** @description Service is not ready */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              ready: false;
              reason: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kubernetes liveness probe
     * @description Returns whether the service process is alive
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is alive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              live: true;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/system/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Simple uptime ping
     * @description Returns 'pong' for uptime monitoring services
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description pong */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record document consent
     * @description Record user consent for a legal document (e.g. terms of service, privacy policy)
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            documentSlug: string;
            documentVersion?: string;
            /**
             * @default EXPLICIT
             * @enum {string}
             */
            consentType?: "EXPLICIT" | "IMPLICIT" | "OPT_IN" | "OPT_OUT";
            context?: string;
            visitorId: string;
            metadata?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Consent recorded successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
              consentId: string;
              documentSlug: string;
              documentVersion: string;
              consentedAt: string;
            };
          };
        };
        /** @description Legal document not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    /**
     * Withdraw consent
     * @description Withdraw previously given consent for a legal document
     */
    delete: {
      parameters: {
        query: {
          documentSlug: string;
          visitorId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Consent withdrawn */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
              withdrawnCount: number;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/consent/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent status
     * @description Check whether a user has consented to a specific legal document and whether re-consent is needed
     */
    get: {
      parameters: {
        query: {
          documentSlug: string;
          visitorId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Consent status retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              hasConsented: boolean;
              consentedVersion: string | null;
              currentVersion: string;
              needsReconsent: boolean;
              lastConsentedAt: string | unknown;
            };
          };
        };
        /** @description Legal document not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/cookie-consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get cookie consent preferences
     * @description Retrieve current cookie consent preferences for a visitor or user
     */
    get: {
      parameters: {
        query?: {
          visitorId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Cookie consent preferences */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              hasConsent: boolean;
              preferences: {
                necessary: boolean;
                functional: boolean;
                analytics: boolean;
                marketing: boolean;
                thirdParty: boolean;
              } | null;
              consentedAt?: string;
              updatedAt?: string;
              expiresAt?: string;
            };
          };
        };
        /** @description Missing required parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Record cookie consent
     * @description Record or update cookie consent preferences for a visitor
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            visitorId: string;
            preferences: {
              /** @default false */
              functional?: boolean;
              /** @default false */
              analytics?: boolean;
              /** @default false */
              marketing?: boolean;
              /** @default false */
              thirdParty?: boolean;
            };
          };
        };
      };
      responses: {
        /** @description Cookie consent recorded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
              consentId: string;
              preferences: {
                necessary: boolean;
                functional: boolean;
                analytics: boolean;
                marketing: boolean;
                thirdParty: boolean;
              };
              consentedAt: string;
              expiresAt: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List legal documents
     * @description List all active legal documents, optionally filtered by locale and type
     */
    get: {
      parameters: {
        query?: {
          locale?: string;
          type?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of legal documents */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              documents: {
                id: string;
                slug: string;
                type: string;
                locale: string;
                version: string;
                title: string;
                summary: string | null;
                effectiveAt: string;
                isRequired: boolean;
              }[];
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/documents/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get legal document
     * @description Retrieve a specific legal document by its slug
     */
    get: {
      parameters: {
        query?: {
          locale?: string;
          version?: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Legal document found */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              document: {
                [key: string]: unknown;
              };
            };
          };
        };
        /** @description Legal document not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/legal/contact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit contact form
     * @description Submit a contact form inquiry. Responses are typically provided within 1-2 business days.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: email */
            email: string;
            company?: string;
            phone?: string;
            subject: string;
            message: string;
            /**
             * @default general
             * @enum {string}
             */
            category?:
              | "general"
              | "sales"
              | "support"
              | "legal"
              | "privacy"
              | "partnership"
              | "press";
          };
        };
      };
      responses: {
        /** @description Contact form submitted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
              submissionId: string;
              message: string;
            };
          };
        };
        /** @description Database error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: {
                code: string;
                message: string;
                details?: {
                  [key: string]: unknown;
                };
              };
              requestId?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/ingest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingest events
     * @description Accepts a batch of events (1-1000) and forwards them to the event ingest service for processing.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            events: {
              eventName: string;
              context: {
                tenantId: string;
                occurredAt: string;
              };
              /** @default {} */
              payload?: {
                [key: string]: unknown;
              };
              eventId?: string;
              /** @default web */
              source?: string;
            }[];
          };
        };
      };
      responses: {
        /** @description Events accepted for processing */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Event ingest service unavailable */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat with an AI agent */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            agentId?: string;
            message: string;
            conversationId?: string;
            /** @default false */
            stream?: boolean;
          };
        };
      };
      responses: {
        /** @description Agent response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              response: string;
              conversationId: string;
              agentId: string;
              usage: {
                promptTokens: number;
                completionTokens: number;
                totalTokens: number;
              };
            };
          };
        };
        /** @description Agent service not configured */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available agents for the current tenant */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Agent list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              agents: {
                id: string;
                name: string;
                description: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List agent conversations for current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Conversation list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              conversations: {
                id: string;
                agentId: string;
                title?: string;
                lastMessage?: string;
                updatedAt: string;
              }[];
            };
          };
        };
        /** @description Agent service not configured */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agents/conversations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete an agent conversation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Conversation deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
        /** @description Agent service not configured */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat completion */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            messages: {
              /** @enum {string} */
              role: "system" | "user" | "assistant";
              content: string;
            }[];
            /** @default gpt-4o */
            model?: string;
            /** @default 0.7 */
            temperature?: number;
            maxTokens?: number;
            /** @default false */
            stream?: boolean;
          };
        };
      };
      responses: {
        /** @description Chat completion response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Quota exceeded */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description AI service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/embeddings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate text embeddings */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            input: string | string[];
            /** @default text-embedding-3-small */
            model?: string;
          };
        };
      };
      responses: {
        /** @description Embeddings response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description AI service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available AI models */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Available models list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/gateway/chat/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Chat completions proxy (API key authenticated)
     * @description Proxy chat completion requests to upstream LLM providers. Requires sk-sailor-* API key.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            model: string;
            messages: {
              /** @enum {string} */
              role: "system" | "user" | "assistant";
              content: string;
            }[];
            /** @default false */
            stream?: boolean;
            temperature?: number;
            max_tokens?: number;
          } & {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Chat completion response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Insufficient credit balance */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Rate limit exceeded */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List API keys for the current organization */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of API keys */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                name: string;
                keyPrefix: string;
                scopes: string[];
                rateLimitRps: number;
                lastUsedAt: string | null;
                revokedAt: string | null;
                expiresAt: string | null;
                createdAt: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new API key
     * @description Returns the full key ONCE. Store it securely — it cannot be retrieved later.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            scopes?: string[];
            rateLimitRps?: number;
            expiresInDays?: number;
          };
        };
      };
      responses: {
        /** @description API key created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              /** @description Full API key — shown only once. Store it securely. */
              key: string;
              name: string;
              keyPrefix: string;
              scopes: string[];
              rateLimitRps: number;
              expiresAt: string | null;
              createdAt: string;
              warning: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/api-keys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke an API key
     * @description Soft-delete: sets revokedAt. Invalidates Redis cache.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Revoked */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              revokedAt: string;
            };
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update API key metadata */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            scopes?: string[];
            rateLimitRps?: number;
          };
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              keyPrefix: string;
              scopes: string[];
              rateLimitRps: number;
              lastUsedAt: string | null;
              revokedAt: string | null;
              expiresAt: string | null;
              createdAt: string;
            };
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  "/api/v1/ai/usage/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Aggregated usage for a billing period */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usage summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              totalTokens: number;
              totalCost: number;
              requestCount: number;
              from: string;
              to: string;
            };
          };
        };
        /** @description Invalid date range */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/usage/by-model": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage breakdown by model */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Per-model usage */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                model: string;
                tokens: number;
                cost: number;
                requests: number;
              }[];
              period: {
                from: string;
                to: string;
              };
            };
          };
        };
        /** @description Invalid date range */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/usage/by-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usage breakdown by API key */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Per-key usage */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                apiKeyId: string;
                name: string;
                keyPrefix: string;
                tokens: number;
                cost: number;
                requests: number;
              }[];
              period: {
                from: string;
                to: string;
              };
            };
          };
        };
        /** @description Invalid date range */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/usage/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Time-series usage (hourly or daily buckets) */
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          granularity?: "hour" | "day";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usage history */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                timestamp: string;
                tokens: number;
                cost: number;
                requests: number;
              }[];
              period: {
                from: string;
                to: string;
              };
            };
          };
        };
        /** @description Invalid date range */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Stripe Checkout session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            priceId: string;
            /** Format: uri */
            successUrl: string;
            /** Format: uri */
            cancelUrl: string;
            trialPeriodDays?: number;
          };
        };
      };
      responses: {
        /** @description Checkout session URL */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              url: string;
              sessionId: string;
            };
          };
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Stripe customer mapping missing */
        424: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Billing service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/portal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Stripe Customer Portal session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: uri */
            returnUrl: string;
          };
        };
      };
      responses: {
        /** @description Billing portal URL */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              url: string;
            };
          };
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Stripe customer mapping missing */
        424: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Billing service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current subscription */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Subscription details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No active subscription */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current usage and limits */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usage data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              period: string;
              apiCalls: {
                used: number;
                limit: number;
                percentUsed: number;
              };
              aiTokens: {
                used: number;
              };
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /**
     * Append an entry to the usage ledger (idempotent)
     * @description Writes a single row to UsageLedgerEntry. The idempotencyKey is mandatory: replaying the same key for the same tenant returns the first-write record untouched with duplicate=true and a 200 status.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            amount: number;
            idempotencyKey: string;
            /**
             * @default API_CALL
             * @enum {string}
             */
            type?: "API_CALL" | "AI_TOKEN" | "STORAGE" | "COMPUTE" | "BANDWIDTH" | "CUSTOM";
            /** @default unit */
            unit?: string;
            metadata?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Duplicate — returning first-write record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              organizationId: string;
              idempotencyKey: string;
              amount: number;
              duplicate: boolean;
            };
          };
        };
        /** @description Ledger row created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              organizationId: string;
              idempotencyKey: string;
              amount: number;
              duplicate: boolean;
            };
          };
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/credits/pricing": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List suggested credit pack tiers
     * @description Public endpoint for marketing display — no authentication required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Credit pack pricing */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              packs: {
                credits: number;
                price: number;
                bonus?: number;
                recommended?: boolean;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/credits/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a credit purchase checkout session
     * @description Creates a provider-agnostic checkout session (Stripe / Polar / LemonSqueezy / ChinaPay). Provider is auto-detected from env.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            creditAmount: number;
            amount: number;
            /** @default USD */
            currency?: string;
            /** Format: uri */
            successUrl: string;
            /** Format: uri */
            cancelUrl: string;
            priceId?: string;
          };
        };
      };
      responses: {
        /** @description Checkout session created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uri */
              url: string;
              sessionId: string;
              provider: string;
            };
          };
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Checkout provider error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
        /** @description Billing service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/credits/balance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current credit balance */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Credit balance */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              balance: number;
              currency: string;
              formatted: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/billing/credits/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List credit transactions (paginated) */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated credit transactions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                id: string;
                organizationId: string;
                type: string;
                amount: number;
                balanceAfter: number;
                description?: string;
                expiresAt?: string;
                relatedId?: string;
                metadata?: {
                  [key: string]: unknown;
                };
                createdAt: string;
              }[];
              meta: {
                total: number;
                hasMore: boolean;
                nextCursor?: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Organization membership required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Perform a full-text search */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            query: string;
            index: string;
            filters?: {
              [key: string]: string | number | boolean;
            };
            facets?: string[];
            sort?: string[];
            page?: number;
            hitsPerPage?: number;
            highlightFields?: string[];
            typoTolerance?: boolean;
            minScore?: number;
          };
        };
      };
      responses: {
        /** @description Search results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Search provider error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Synchronize database with search index */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sync triggered */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all integrations for the current organization */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of integrations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new integration */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            type: "SHOPIFY" | "SHOPLINE" | "STRIPE" | "CUSTOM";
            name: string;
            credentials?: {
              [key: string]: unknown;
            };
            settings?: {
              [key: string]: unknown;
            };
          };
        };
      };
      responses: {
        /** @description Integration created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Integration already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/integrations/:id": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get integration by ID (returns decrypted credentials and settings) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Integration details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete an integration */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Integration deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update an integration */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            credentials?: {
              [key: string]: unknown;
            };
            settings?: {
              [key: string]: unknown;
            };
            isActive?: boolean;
          };
        };
      };
      responses: {
        /** @description Updated integration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  "/api/v1/admin/tenants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all organizations */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number | null;
          plan?: "FREE" | "PRO" | "ENTERPRISE";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Organization list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tenants/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get organization details with live usage */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Organization details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tenants/{id}/suspend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspend an organization (block API access) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Suspended */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/tenants/{id}/unsuspend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a suspended organization */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unsuspended */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/usage/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cross-tenant usage report for current billing period */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usage report */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/dlq": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List dead letter queue entries */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description DLQ entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/dlq/{id}/ack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Acknowledge a DLQ entry (remove from queue) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Acknowledged */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/feature-flags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List per-tenant feature flag overrides */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Feature flag overrides */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Set a per-tenant feature flag override */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            organizationId: string;
            flag: string;
            enabled: boolean;
          };
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/webhooks/stripe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stripe webhook handler
     * @description Receives Stripe webhook events for subscription lifecycle management. Signature verification is handled by the Stripe SDK.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Webhook received and queued for processing */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              received: true;
              skipped?: boolean;
            };
          };
        };
        /** @description Invalid signature or missing headers */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Webhook not configured */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/webhooks/clerk": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clerk webhook handler
     * @description Receives Clerk webhook events for user and organization lifecycle management. Signature verification is handled by the Svix SDK.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Webhook received and queued for processing */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {boolean} */
              received: true;
              skipped?: boolean;
            };
          };
        };
        /** @description Invalid signature or missing svix headers */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Webhook not configured */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
