/**
 * Nebutra Brand Metadata
 * Central source of truth for brand identity
 *
 * AUTO-GENERATED by `pnpm brand:apply` from `scripts/brand-types.ts`
 * (DEFAULT_BRAND) or a sibling `brand.config.ts` if present. Do NOT
 * edit by hand — your edits will be wiped on the next brand:apply.
 *
 * To rebrand, edit DEFAULT_BRAND in scripts/brand-types.ts and run
 * `pnpm brand:apply`. To extend the shape, add a field to BrandConfig,
 * set its value in DEFAULT_BRAND, then read it from this writer.
 *
 * Pipeline guard: tests/architecture/brand-metadata-drift.test.ts
 * asserts `metadata.ts` is byte-identical to what brand:apply emits.
 */

export const brand = {
  name: "Nebutra",
  nameCn: "云毓智能",
  nameFull: "无锡云毓智能科技有限公司",
  nameFullEn: "Wuxi Nebutra Intelligent Technology Co., Ltd.",

  tagline: "Ship AI products, not boilerplate.",
  taglineCn: "AI原生·快速出海·即刻交付",
  description:
    "Production-ready Next.js monorepo template for AI SaaS products. Auth, billing, multi-tenancy, AI services, design system, and enterprise infrastructure — pre-configured.",
  descriptionCn:
    "面向AI创业者的一体化SaaS基础设施模板，覆盖认证、计费、多租户、AI服务与设计系统，开箱即产品",

  story: {
    concept:
      "Logo以首字母N的基础造型概念为主要设计框架，通过几何正负空间构建隐形'N'，形成近似六边形的稳定结构",
    colorMeaning: "蓝绿渐变体现未来感与科技锋芒，'云'代表云端平台，'毓'寓意孕育与转化",
    values: ["AI Native", "Ship Fast", "Open by Default", "Global-Ready", "Enterprise-Grade"],
    missionStatement:
      "Help AI founders and SaaS teams go from idea to production 10x faster by providing the infrastructure layer they shouldn't have to build.",
  },

  domains: {
    landing: "nebutra.com",
    app: "app.nebutra.com",
    api: "api.nebutra.com",
    studio: "studio.nebutra.com",
    cdn: "cdn.nebutra.com",
  },

  social: {
    twitter: "https://twitter.com/nebutra",
    github: "https://github.com/nebutra",
    discord: "https://discord.gg/nebutra",
    linkedin: "https://linkedin.com/company/nebutra",
  },
} as const;

/**
 * Brand Colors — full VI palette + brand gradients + semantic colors.
 * Aligned with @nebutra/design-tokens DTCG SSOT (tokens/core.json).
 */
export const colors = {
  primary: {
    "50": "#f0f4ff",
    "100": "#dbe4ff",
    "200": "#bac8ff",
    "300": "#91a7ff",
    "400": "#5c7cfa",
    "500": "#0033FE",
    "600": "#002ad4",
    "700": "#0021ab",
    "800": "#001882",
    "900": "#000f59",
    "950": "#000830",
  },
  accent: {
    "50": "#e6fff8",
    "100": "#b3ffec",
    "200": "#80ffe0",
    "300": "#4dfcd4",
    "400": "#1af7c8",
    "500": "#0BF1C3",
    "600": "#09c9a3",
    "700": "#07a183",
    "800": "#057963",
    "900": "#035143",
    "950": "#012923",
  },
  neutral: {
    "0": "#ffffff",
    "50": "#f8fafc",
    "100": "#f1f5f9",
    "200": "#e2e8f0",
    "300": "#cbd5e1",
    "400": "#94a3b8",
    "500": "#64748b",
    "600": "#475569",
    "700": "#334155",
    "800": "#1e293b",
    "900": "#0f172a",
    "950": "#020617",
  },
  white: "#FFFFFF",
  black: "#000000",
  gradient: {
    primary: "linear-gradient(135deg, #0033FE 0%, #0BF1C3 100%)",
    primaryReverse: "linear-gradient(135deg, #0BF1C3 0%, #0033FE 100%)",
    primaryVertical: "linear-gradient(180deg, #0033FE 0%, #0BF1C3 100%)",
    primaryRadial: "radial-gradient(circle, #0BF1C3 0%, #0033FE 100%)",
  },
  success: "#22c55e",
  warning: "#f59e0b",
  error: "#ef4444",
  info: "#0033FE",
} as const;

/**
 * Typography — "Precision Stack" (Geist + Noto Sans SC + Geist Mono).
 */
export const typography = {
  fontFamily: {
    en: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
    cn: '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", "vivo Sans", sans-serif',
    sans: '"Geist", "Noto Sans SC", "PingFang SC", "Microsoft YaHei", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    mono: '"Geist Mono", "Fira Code", ui-monospace, Consolas, "Courier New", monospace',
    display: '"Geist", "Noto Sans SC", sans-serif',
    heading: '"Geist", "Noto Sans SC", sans-serif',
    brandPrint: '"vivo Sans", "PingFang SC", sans-serif',
  },
  cssVars: {
    sans: "var(--font-geist-sans)",
    mono: "var(--font-geist-mono)",
    cnSans: "var(--font-noto-sc)",
  },
  fontWeight: {
    thin: 100,
    extraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
  },
  letterSpacing: {
    display: "-0.04em",
    heading: "-0.03em",
    subheading: "-0.02em",
    body: "0em",
    caption: "0.01em",
    mono: "0em",
  },
  lineHeight: {
    none: 1,
    tight: 1.2,
    snug: 1.4,
    normal: 1.6,
    relaxed: 1.75,
    loose: 2,
  },
} as const;

/**
 * Logo asset paths (relative to package), dual-edition structure:
 *   - classic (v1.0): preferred for UX / product surfaces
 *   - compliant (v2.0): required for commercial / legal contexts
 */
export const logoAssets = {
  classic: {
    default: "assets/logo/logo-color.svg",
    color: "assets/logo/logo-color.svg",
    inverse: "assets/logo/logo-inverse.svg",
    mono: "assets/logo/logo-mono.svg",
    en: "assets/logo/logo-en.svg",
    zh: "assets/logo/logo-zh.svg",
    zhEn: "assets/logo/logo-zh-en.svg",
    horizontalEn: "assets/logo/logo-horizontal-en.svg",
    horizontalZh: "assets/logo/logo-horizontal-zh.svg",
    verticalEn: "assets/logo/logo-vertical-en.svg",
    verticalZh: "assets/logo/logo-vertical-zh.svg",
  },
  compliant: {
    default: "assets/logo-compliant/logo-color.svg",
    color: "assets/logo-compliant/logo-color.svg",
    inverse: "assets/logo-compliant/logo-inverse.svg",
    mono: "assets/logo-compliant/logo-mono.svg",
    en: "assets/logo-compliant/logo-en.svg",
    zh: "assets/logo-compliant/logo-zh.svg",
    zhEn: "assets/logo-compliant/logo-zh-en.svg",
    horizontalEn: "assets/logo-compliant/logo-horizontal-en.svg",
    horizontalZh: "assets/logo-compliant/logo-horizontal-zh.svg",
    verticalEn: "assets/logo-compliant/logo-vertical-en.svg",
    verticalZh: "assets/logo-compliant/logo-vertical-zh.svg",
    horizontalEnMono: "assets/logo-compliant/logo-horizontal-en-mono.svg",
    horizontalZhMono: "assets/logo-compliant/logo-horizontal-zh-mono.svg",
    verticalEnMono: "assets/logo-compliant/logo-vertical-en-mono.svg",
    verticalZhMono: "assets/logo-compliant/logo-vertical-zh-mono.svg",
  },
} as const;

/**
 * Font asset paths (relative to package).
 */
export const fontAssets = {
  poppins: {
    thin: "assets/fonts/poppins/Poppins-Thin.otf",
    thinItalic: "assets/fonts/poppins/Poppins-ThinItalic.otf",
    extraLight: "assets/fonts/poppins/Poppins-ExtraLight.otf",
    extraLightItalic: "assets/fonts/poppins/Poppins-ExtraLightItalic.otf",
    light: "assets/fonts/poppins/Poppins-Light.otf",
    lightItalic: "assets/fonts/poppins/Poppins-LightItalic.otf",
    regular: "assets/fonts/poppins/Poppins-Regular.otf",
    italic: "assets/fonts/poppins/Poppins-Italic.otf",
    medium: "assets/fonts/poppins/Poppins-Medium.otf",
    mediumItalic: "assets/fonts/poppins/Poppins-MediumItalic.otf",
    semiBold: "assets/fonts/poppins/Poppins-SemiBold.otf",
    semiBoldItalic: "assets/fonts/poppins/Poppins-SemiBoldItalic.otf",
    bold: "assets/fonts/poppins/Poppins-Bold.otf",
    boldItalic: "assets/fonts/poppins/Poppins-BoldItalic.otf",
    extraBold: "assets/fonts/poppins/Poppins-ExtraBold.otf",
    extraBoldItalic: "assets/fonts/poppins/Poppins-ExtraBoldItalic.otf",
    black: "assets/fonts/poppins/Poppins-Black.otf",
    blackItalic: "assets/fonts/poppins/Poppins-BlackItalic.otf",
  },
  vivoSans: {
    thin: "assets/fonts/vivo-sans/vivoSans-Thin.ttf",
    extraLight: "assets/fonts/vivo-sans/vivoSans-ExtraLight.ttf",
    light: "assets/fonts/vivo-sans/vivoSans-Light.ttf",
    regular: "assets/fonts/vivo-sans/vivoSans-Regular.ttf",
    medium: "assets/fonts/vivo-sans/vivoSans-Medium.ttf",
    demiBold: "assets/fonts/vivo-sans/vivoSans-DemiBold.ttf",
    bold: "assets/fonts/vivo-sans/vivoSans-Bold.ttf",
    extraBold: "assets/fonts/vivo-sans/vivoSans-ExtraBold.ttf",
    heavy: "assets/fonts/vivo-sans/vivoSans-Heavy.ttf",
  },
} as const;

/**
 * Favicon assets.
 */
export const faviconAssets = {
  ico: "assets/favicon/favicon.ico",
  svg: "assets/favicon/favicon.svg",
  apple: "assets/favicon/apple-touch-icon.png",
  android192: "assets/favicon/android-chrome-192x192.png",
  android512: "assets/favicon/android-chrome-512x512.png",
} as const;

/**
 * OG Image dimensions.
 */
export const ogImageDimensions = {
  default: {
    width: 1200,
    height: 630,
  },
  twitter: {
    width: 1200,
    height: 600,
  },
  square: {
    width: 1200,
    height: 1200,
  },
} as const;

export type BrandColors = typeof colors;
export type BrandTypography = typeof typography;
export type LogoAssets = typeof logoAssets;
