/**
 * AUTO-GENERATED by scripts/sync-product-locales.mjs — do not hand-edit.
 * Source of truth: packages/platform/i18n/locales/*.json
 */
export const PRODUCT_MESSAGE_LOCALES = ["de", "en", "es", "fr", "ja", "ko", "zh"] as const;

export type ProductMessageLocale = (typeof PRODUCT_MESSAGE_LOCALES)[number];

export const DEFAULT_PRODUCT_MESSAGE_LOCALE = "en" as const;
