/**
 * AUTO-GENERATED by scripts/i18n-seed-product-locales.mjs — do not hand-edit.
 * Source of truth: packages/platform/i18n/locales/*.json
 * Chinese catalogs: zh-Hans (Simplified) + zh-Hant (Traditional) — CLDR multi-script.
 */
export const PRODUCT_MESSAGE_LOCALES = [
  "ar",
  "bn",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "fa",
  "fi",
  "fr",
  "he",
  "hi",
  "hu",
  "id",
  "it",
  "ja",
  "ko",
  "ms",
  "nl",
  "no",
  "pl",
  "pt",
  "ro",
  "ru",
  "sv",
  "sw",
  "th",
  "tr",
  "uk",
  "ur",
  "vi",
  "zh-Hans",
  "zh-Hant",
] as const;

export type ProductMessageLocale = (typeof PRODUCT_MESSAGE_LOCALES)[number];

export const DEFAULT_PRODUCT_MESSAGE_LOCALE = "en" as const;
