import { describe, expect, it } from "vitest";
import { brand, colors } from "../../packages/design/brand/src/metadata";

/**
 * Phase 2 — Brand config facts gate (contract lock).
 *
 * Locks the `@nebutra/brand` identity contract that the app-identity helpers
 * (Phase 3) and the i18n variabilization (Phase 4) depend on. No production
 * code — a downstream rename of an exported field fails fast HERE rather than
 * silently breaking every consumer.
 *
 * `metadata.ts` is auto-generated by `pnpm brand:apply` from `DEFAULT_BRAND`
 * in `scripts/brand-types.ts`. If a field is intentionally renamed, update this
 * test in the same change — it is the authoritative consumed-contract.
 */

const HEX = /^#[0-9a-fA-F]{6}$/;

describe("brand config facts (contract lock for app helpers + i18n)", () => {
  it("brand exposes the identity strings consumers read", () => {
    for (const key of [
      "name",
      "nameCn",
      "nameFull",
      "nameFullEn",
      "tagline",
      "description",
    ] as const) {
      expect(typeof brand[key], `brand.${key}`).toBe("string");
      expect(brand[key].length, `brand.${key} non-empty`).toBeGreaterThan(0);
    }
  });

  it("brand.domains carries every service host", () => {
    for (const key of [
      "landing",
      "app",
      "api",
      "auth",
      "sso",
      "docs",
      "studio",
      "cdn",
      "router",
      "forge",
      "design",
      "status",
      "analytics",
    ] as const) {
      expect(typeof brand.domains[key], `brand.domains.${key}`).toBe("string");
      expect(brand.domains[key].length).toBeGreaterThan(0);
    }
  });

  it("brand.social carries every channel", () => {
    for (const key of ["twitter", "github", "discord", "linkedin"] as const) {
      expect(typeof brand.social[key], `brand.social.${key}`).toBe("string");
      expect(brand.social[key].length).toBeGreaterThan(0);
    }
  });

  it("colors expose the brand + neutral anchors as hex", () => {
    expect(colors.primary["500"], "colors.primary.500").toMatch(HEX);
    expect(colors.accent["500"], "colors.accent.500").toMatch(HEX);
    expect(colors.neutral["950"], "colors.neutral.950").toMatch(HEX);
  });
});
