import { type Specimen, SpecimenSchema } from "./schema";

const RAW_SPECIMENS: Specimen[] = [
  {
    id: "spec-calm-saas-landing",
    workId: "work-calm-saas-landing",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 600 },
      { typefaceId: "source-sans-3", role: "body", weight: 400 },
      { typefaceId: "source-sans-3", role: "headline", weight: 600 },
    ],
    pairing: { strategy: "Soft display serif + neutral sans body", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 3.5, weight: 600, tracking: "-0.02em", leading: 1.1 },
      { role: "headline", rem: 1.5, weight: 600, leading: 1.25 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.65 },
      { role: "caption", rem: 0.875, weight: 400, leading: 1.4 },
    ],
    tags: ["saas-landing", "calm-tech", "latin", "website"],
    confidence: 0.9,
    verifiedBy: "human",
    summary: "Calm SaaS: Fraunces hero, Source Sans 3 body.",
    summaryZh: "冷静 SaaS：Fraunces 英雄标题，Source Sans 3 正文。",
  },
  {
    id: "spec-zh-product-site",
    workId: "work-zh-product-site",
    typefaces: [
      { typefaceId: "source-han-sans", role: "body", weight: 400 },
      { typefaceId: "source-han-sans", role: "headline", weight: 600 },
      { typefaceId: "space-grotesk", role: "display", weight: 500 },
      { typefaceId: "geist-mono", role: "mono", weight: 400 },
    ],
    pairing: { strategy: "CJK UI sans + Latin geometric wordmark", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 2.75, weight: 500, tracking: "-0.01em", leading: 1.15 },
      { role: "headline", rem: 1.375, weight: 600, leading: 1.35 },
      { role: "body", rem: 1, weight: 400, leading: 1.7 },
      { role: "mono", rem: 0.875, weight: 400, leading: 1.5 },
    ],
    tags: ["zh-marketing", "bilingual", "saas", "website", "cjk-hans"],
    confidence: 0.88,
    verifiedBy: "human",
    summary: "Chinese product site: Source Han Sans UI, Space Grotesk brand.",
    summaryZh: "中文产品站：思源黑体 + Space Grotesk 品牌点缀。",
  },
  {
    id: "spec-conference-poster",
    workId: "work-conference-poster",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 700 },
      { typefaceId: "space-grotesk", role: "headline", weight: 500 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Expressive serif display + geometric meta", contrast: "high" },
    hierarchy: [
      { role: "display", rem: 4.5, weight: 700, tracking: "-0.03em", leading: 1.05 },
      { role: "headline", rem: 1.25, weight: 500, tracking: "0.04em", leading: 1.2 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.3 },
    ],
    tags: ["poster", "event", "editorial", "latin", "high-contrast"],
    confidence: 0.92,
    verifiedBy: "human",
    summary: "Conference poster: Fraunces + Space Grotesk + Inter.",
    summaryZh: "大会海报：Fraunces + Space Grotesk。",
  },
  {
    id: "spec-bilingual-brand-poster",
    workId: "work-bilingual-brand-poster",
    typefaces: [
      { typefaceId: "noto-serif-sc", role: "display", weight: 600 },
      { typefaceId: "space-grotesk", role: "headline", weight: 500 },
      { typefaceId: "lxgw-wenkai", role: "accent", weight: 400 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "SC serif hero + Latin geometric + Kai accent", contrast: "high" },
    hierarchy: [
      { role: "display", rem: 3.25, weight: 600, leading: 1.2 },
      { role: "headline", rem: 1.125, weight: 500, tracking: "0.06em", leading: 1.25 },
      { role: "accent", rem: 1.25, weight: 400, leading: 1.5 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.35 },
    ],
    tags: ["poster", "bilingual", "brand", "cjk-hans", "latin", "cultural"],
    confidence: 0.87,
    verifiedBy: "hybrid",
    summary: "Bilingual brand poster: Noto Serif SC + Space Grotesk + Kai.",
    summaryZh: "中西文品牌海报：Noto 宋体 + Space Grotesk + 文楷。",
  },
  {
    id: "spec-dev-docs",
    workId: "work-dev-docs",
    typefaces: [
      { typefaceId: "inter", role: "body", weight: 400 },
      { typefaceId: "inter", role: "headline", weight: 600 },
      { typefaceId: "jetbrains-mono", role: "mono", weight: 400 },
    ],
    pairing: { strategy: "Neutral UI sans + purpose mono", contrast: "low" },
    hierarchy: [
      { role: "headline", rem: 1.75, weight: 600, leading: 1.25 },
      { role: "body", rem: 1, weight: 400, leading: 1.7 },
      { role: "mono", rem: 0.875, weight: 400, leading: 1.55 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["docs", "developer-tools", "website", "latin", "mono"],
    confidence: 0.93,
    verifiedBy: "human",
    summary: "Docs: Inter chrome, JetBrains Mono code.",
    summaryZh: "文档壳：Inter + JetBrains Mono。",
  },
  {
    id: "spec-editorial-blog",
    workId: "work-editorial-blog",
    typefaces: [
      { typefaceId: "newsreader", role: "body", weight: 400 },
      { typefaceId: "newsreader", role: "display", weight: 500 },
      { typefaceId: "source-sans-3", role: "headline", weight: 600 },
      { typefaceId: "source-sans-3", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Editorial serif body + sans chrome", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 2.5, weight: 500, leading: 1.2 },
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 1.125, weight: 400, leading: 1.75 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["editorial", "blog", "longform", "website", "latin"],
    confidence: 0.9,
    verifiedBy: "human",
    summary: "Blog: Newsreader longform, Source Sans 3 chrome.",
    summaryZh: "博客：Newsreader + Source Sans 3。",
  },
  {
    id: "spec-startup-pitch-poster",
    workId: "work-startup-pitch-poster",
    typefaces: [
      { typefaceId: "dm-sans", role: "display", weight: 700 },
      { typefaceId: "ibm-plex-sans", role: "headline", weight: 500 },
      { typefaceId: "ibm-plex-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Geometric display + plex meta", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 4, weight: 700, tracking: "-0.025em", leading: 1.05 },
      { role: "headline", rem: 1.125, weight: 500, leading: 1.25 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.3 },
    ],
    tags: ["poster", "startup", "event", "latin", "energetic"],
    confidence: 0.86,
    verifiedBy: "human",
    summary: "Pitch poster: DM Sans + IBM Plex Sans.",
    summaryZh: "路演海报：DM Sans + IBM Plex。",
  },
  {
    id: "spec-zh-dashboard-ui",
    workId: "work-zh-dashboard-ui",
    typefaces: [
      { typefaceId: "noto-sans-sc", role: "body", weight: 400 },
      { typefaceId: "noto-sans-sc", role: "headline", weight: 600 },
      { typefaceId: "jetbrains-mono", role: "mono", weight: 400 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "SC UI sans + mono machine strings", contrast: "low" },
    hierarchy: [
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 0.9375, weight: 400, leading: 1.5 },
      { role: "mono", rem: 0.8125, weight: 400, leading: 1.45 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.35 },
    ],
    tags: ["app-ui", "dashboard", "cjk-hans", "bilingual", "saas"],
    confidence: 0.91,
    verifiedBy: "human",
    summary: "Dashboard: Noto Sans SC + JetBrains Mono.",
    summaryZh: "控制台：Noto Sans SC + JetBrains Mono。",
  },
];
export const SPECIMENS: readonly Specimen[] = RAW_SPECIMENS.map((s) => SpecimenSchema.parse(s));
export const SPECIMEN_BY_ID: ReadonlyMap<string, Specimen> = new Map(
  SPECIMENS.map((s) => [s.id, s]),
);
