import { FIU_SPECIMENS } from "./fiu-load";
import { type Specimen, SpecimenSchema } from "./schema";

const RAW_SPECIMENS: Specimen[] = [
  {
    id: "spec-calm-saas-landing",
    workId: "work-calm-saas-landing",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 600 },
      { typefaceId: "source-sans-3", role: "body", weight: 400 },
      { typefaceId: "source-sans-3", role: "headline", weight: 600 },
    ],
    pairing: { strategy: "Soft display serif + neutral sans body", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 3.5, weight: 600, tracking: "-0.02em", leading: 1.1 },
      { role: "headline", rem: 1.5, weight: 600, leading: 1.25 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.65 },
      { role: "caption", rem: 0.875, weight: 400, leading: 1.4 },
    ],
    tags: ["saas-landing", "calm-tech", "latin", "website"],
    confidence: 0.9,
    verifiedBy: "human",
    summary: "Calm SaaS: Fraunces hero, Source Sans 3 body.",
    summaryZh: "冷静 SaaS：Fraunces 英雄标题，Source Sans 3 正文。",
  },
  {
    id: "spec-zh-product-site",
    workId: "work-zh-product-site",
    typefaces: [
      { typefaceId: "source-han-sans", role: "body", weight: 400 },
      { typefaceId: "source-han-sans", role: "headline", weight: 600 },
      { typefaceId: "space-grotesk", role: "display", weight: 500 },
      { typefaceId: "geist-mono", role: "mono", weight: 400 },
    ],
    pairing: { strategy: "CJK UI sans + Latin geometric wordmark", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 2.75, weight: 500, tracking: "-0.01em", leading: 1.15 },
      { role: "headline", rem: 1.375, weight: 600, leading: 1.35 },
      { role: "body", rem: 1, weight: 400, leading: 1.7 },
      { role: "mono", rem: 0.875, weight: 400, leading: 1.5 },
    ],
    tags: ["zh-marketing", "bilingual", "saas", "website", "cjk-hans"],
    confidence: 0.88,
    verifiedBy: "human",
    summary: "Chinese product site: Source Han Sans UI, Space Grotesk brand.",
    summaryZh: "中文产品站：思源黑体 + Space Grotesk 品牌点缀。",
  },
  {
    id: "spec-conference-poster",
    workId: "work-conference-poster",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 700 },
      { typefaceId: "space-grotesk", role: "headline", weight: 500 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Expressive serif display + geometric meta", contrast: "high" },
    hierarchy: [
      { role: "display", rem: 4.5, weight: 700, tracking: "-0.03em", leading: 1.05 },
      { role: "headline", rem: 1.25, weight: 500, tracking: "0.04em", leading: 1.2 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.3 },
    ],
    tags: ["poster", "event", "editorial", "latin", "high-contrast"],
    confidence: 0.92,
    verifiedBy: "human",
    summary: "Conference poster: Fraunces + Space Grotesk + Inter.",
    summaryZh: "大会海报：Fraunces + Space Grotesk。",
  },
  {
    id: "spec-bilingual-brand-poster",
    workId: "work-bilingual-brand-poster",
    typefaces: [
      { typefaceId: "noto-serif-sc", role: "display", weight: 600 },
      { typefaceId: "space-grotesk", role: "headline", weight: 500 },
      { typefaceId: "lxgw-wenkai", role: "accent", weight: 400 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "SC serif hero + Latin geometric + Kai accent", contrast: "high" },
    hierarchy: [
      { role: "display", rem: 3.25, weight: 600, leading: 1.2 },
      { role: "headline", rem: 1.125, weight: 500, tracking: "0.06em", leading: 1.25 },
      { role: "accent", rem: 1.25, weight: 400, leading: 1.5 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.35 },
    ],
    tags: ["poster", "bilingual", "brand", "cjk-hans", "latin", "cultural"],
    confidence: 0.87,
    verifiedBy: "hybrid",
    summary: "Bilingual brand poster: Noto Serif SC + Space Grotesk + Kai.",
    summaryZh: "中西文品牌海报：Noto 宋体 + Space Grotesk + 文楷。",
  },
  {
    id: "spec-dev-docs",
    workId: "work-dev-docs",
    typefaces: [
      { typefaceId: "inter", role: "body", weight: 400 },
      { typefaceId: "inter", role: "headline", weight: 600 },
      { typefaceId: "jetbrains-mono", role: "mono", weight: 400 },
    ],
    pairing: { strategy: "Neutral UI sans + purpose mono", contrast: "low" },
    hierarchy: [
      { role: "headline", rem: 1.75, weight: 600, leading: 1.25 },
      { role: "body", rem: 1, weight: 400, leading: 1.7 },
      { role: "mono", rem: 0.875, weight: 400, leading: 1.55 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["docs", "developer-tools", "website", "latin", "mono"],
    confidence: 0.93,
    verifiedBy: "human",
    summary: "Docs: Inter chrome, JetBrains Mono code.",
    summaryZh: "文档壳：Inter + JetBrains Mono。",
  },
  {
    id: "spec-editorial-blog",
    workId: "work-editorial-blog",
    typefaces: [
      { typefaceId: "newsreader", role: "body", weight: 400 },
      { typefaceId: "newsreader", role: "display", weight: 500 },
      { typefaceId: "source-sans-3", role: "headline", weight: 600 },
      { typefaceId: "source-sans-3", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Editorial serif body + sans chrome", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 2.5, weight: 500, leading: 1.2 },
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 1.125, weight: 400, leading: 1.75 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["editorial", "blog", "longform", "website", "latin"],
    confidence: 0.9,
    verifiedBy: "human",
    summary: "Blog: Newsreader longform, Source Sans 3 chrome.",
    summaryZh: "博客：Newsreader + Source Sans 3。",
  },
  {
    id: "spec-startup-pitch-poster",
    workId: "work-startup-pitch-poster",
    typefaces: [
      { typefaceId: "dm-sans", role: "display", weight: 700 },
      { typefaceId: "ibm-plex-sans", role: "headline", weight: 500 },
      { typefaceId: "ibm-plex-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Geometric display + plex meta", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 4, weight: 700, tracking: "-0.025em", leading: 1.05 },
      { role: "headline", rem: 1.125, weight: 500, leading: 1.25 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.3 },
    ],
    tags: ["poster", "startup", "event", "latin", "energetic"],
    confidence: 0.86,
    verifiedBy: "human",
    summary: "Pitch poster: DM Sans + IBM Plex Sans.",
    summaryZh: "路演海报：DM Sans + IBM Plex。",
  },
  {
    id: "spec-zh-dashboard-ui",
    workId: "work-zh-dashboard-ui",
    typefaces: [
      { typefaceId: "noto-sans-sc", role: "body", weight: 400 },
      { typefaceId: "noto-sans-sc", role: "headline", weight: 600 },
      { typefaceId: "jetbrains-mono", role: "mono", weight: 400 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "SC UI sans + mono machine strings", contrast: "low" },
    hierarchy: [
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 0.9375, weight: 400, leading: 1.5 },
      { role: "mono", rem: 0.8125, weight: 400, leading: 1.45 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.35 },
    ],
    tags: ["app-ui", "dashboard", "cjk-hans", "bilingual", "saas"],
    confidence: 0.91,
    verifiedBy: "human",
    summary: "Dashboard: Noto Sans SC + JetBrains Mono.",
    summaryZh: "控制台：Noto Sans SC + JetBrains Mono。",
  },

  // --- FIU metadata cold-start ---
  {
    id: "spec-fiu-vercel-website",
    workId: "work-fiu-vercel-website",
    typefaces: [
      { typefaceId: "inter", role: "display", weight: 700 },
      { typefaceId: "inter", role: "headline", weight: 600 },
      { typefaceId: "inter", role: "body", weight: 400 },
      { typefaceId: "inter", role: "caption", weight: 400 },
    ],
    pairing: {
      strategy: "Single-family variable Inter system",
      contrast: "harmonious",
      notes: "Weight + tracking do the hierarchy; free commercial.",
    },
    hierarchy: [
      { role: "display", rem: 3.5, weight: 700, tracking: "-0.03em", leading: 1.05 },
      { role: "headline", rem: 1.5, weight: 600, leading: 1.2 },
      { role: "body", rem: 1, weight: 400, leading: 1.6 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: [
      "fiu-coldstart",
      "single-family",
      "variable-fonts",
      "website",
      "developer-tools",
      "latin",
    ],
    confidence: 0.72,
    verifiedBy: "hybrid",
    summary: "Vercel-style product site: Inter across all roles.",
    summaryZh: "Vercel 风格产品站：Inter 全角色系统。",
  },
  {
    id: "spec-fiu-vksplan-website",
    workId: "work-fiu-vksplan-website",
    typefaces: [
      { typefaceId: "dm-sans", role: "display", weight: 600 },
      { typefaceId: "dm-sans", role: "headline", weight: 500 },
      { typefaceId: "dm-sans", role: "body", weight: 400 },
    ],
    pairing: { strategy: "Single-family DM Sans product UI", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 2.75, weight: 600, leading: 1.1 },
      { role: "headline", rem: 1.375, weight: 500, leading: 1.25 },
      { role: "body", rem: 1, weight: 400, leading: 1.6 },
    ],
    tags: ["fiu-coldstart", "single-family", "website", "latin"],
    confidence: 0.6,
    verifiedBy: "hybrid",
    summary: "VKSplan site: DM Sans system.",
    summaryZh: "VKSplan 站点：DM Sans 系统。",
  },
  {
    id: "spec-fiu-taylor-roy-portfolio",
    workId: "work-fiu-taylor-roy-portfolio",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 600 },
      { typefaceId: "fraunces", role: "headline", weight: 500 },
      { typefaceId: "fraunces", role: "body", weight: 400 },
    ],
    pairing: { strategy: "Soft optical display family as portfolio voice", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 3.25, weight: 600, leading: 1.1 },
      { role: "headline", rem: 1.5, weight: 500, leading: 1.25 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.65 },
    ],
    tags: ["fiu-coldstart", "single-family", "portfolio", "website", "latin"],
    confidence: 0.6,
    verifiedBy: "hybrid",
    summary: "Portfolio: Fraunces as voice and body.",
    summaryZh: "作品集：Fraunces 统一声线。",
  },
  {
    id: "spec-fiu-northmed-identity",
    workId: "work-fiu-northmed-identity",
    typefaces: [
      { typefaceId: "ibm-plex-sans", role: "display", weight: 600 },
      { typefaceId: "ibm-plex-sans", role: "headline", weight: 500 },
      { typefaceId: "ibm-plex-sans", role: "body", weight: 400 },
    ],
    pairing: { strategy: "IBM Plex Sans identity system", contrast: "low" },
    hierarchy: [
      { role: "display", rem: 2.5, weight: 600, leading: 1.15 },
      { role: "headline", rem: 1.25, weight: 500, leading: 1.3 },
      { role: "body", rem: 1, weight: 400, leading: 1.55 },
    ],
    tags: ["fiu-coldstart", "single-family", "brand-identity", "latin"],
    confidence: 0.58,
    verifiedBy: "hybrid",
    summary: "NorthMed identity: IBM Plex Sans.",
    summaryZh: "NorthMed 视觉识别：IBM Plex Sans。",
  },
  {
    id: "spec-fiu-bel-canto",
    workId: "work-fiu-bel-canto",
    typefaces: [
      { typefaceId: "playfair-display", role: "display", weight: 700 },
      { typefaceId: "playfair-display", role: "headline", weight: 600 },
      { typefaceId: "playfair-display", role: "body", weight: 400 },
    ],
    pairing: { strategy: "Playfair Display editorial voice", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 3.75, weight: 700, tracking: "-0.02em", leading: 1.08 },
      { role: "headline", rem: 1.5, weight: 600, leading: 1.25 },
      { role: "body", rem: 1.125, weight: 400, leading: 1.7 },
    ],
    tags: ["fiu-coldstart", "single-family", "editorial", "latin"],
    confidence: 0.58,
    verifiedBy: "hybrid",
    summary: "Bel Canto editorial: Playfair Display.",
    summaryZh: "美声编辑向：Playfair Display。",
  },
  {
    id: "spec-fiu-we-are-water",
    workId: "work-fiu-we-are-water",
    typefaces: [
      { typefaceId: "playfair-display", role: "display", weight: 600 },
      { typefaceId: "playfair-display", role: "headline", weight: 500 },
      { typefaceId: "playfair-display", role: "body", weight: 400 },
    ],
    pairing: { strategy: "Report system on Playfair Display", contrast: "harmonious" },
    hierarchy: [
      { role: "display", rem: 2.75, weight: 600, leading: 1.15 },
      { role: "headline", rem: 1.375, weight: 500, leading: 1.3 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.65 },
    ],
    tags: ["fiu-coldstart", "single-family", "editorial", "report", "latin"],
    confidence: 0.58,
    verifiedBy: "hybrid",
    summary: "Activity report: Playfair Display system.",
    summaryZh: "活动报告：Playfair Display 系统。",
  },
  {
    id: "spec-free-editorial-serif-sans",
    workId: "work-free-editorial-serif-sans",
    typefaces: [
      { typefaceId: "newsreader", role: "display", weight: 500 },
      { typefaceId: "newsreader", role: "body", weight: 400 },
      { typefaceId: "public-sans", role: "headline", weight: 600 },
      { typefaceId: "public-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Editorial serif story + public sans chrome", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 2.75, weight: 500, leading: 1.15 },
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 1.125, weight: 400, leading: 1.75 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["coldstart", "multi-family", "editorial", "website", "latin", "free-commercial"],
    confidence: 0.88,
    verifiedBy: "human",
    summary: "Open editorial: Newsreader + Public Sans.",
    summaryZh: "开放编辑：Newsreader + Public Sans。",
  },
  {
    id: "spec-free-saas-grotesk-stack",
    workId: "work-free-saas-grotesk-stack",
    typefaces: [
      { typefaceId: "space-grotesk", role: "display", weight: 500 },
      { typefaceId: "inter", role: "headline", weight: 600 },
      { typefaceId: "inter", role: "body", weight: 400 },
      { typefaceId: "jetbrains-mono", role: "mono", weight: 400 },
    ],
    pairing: { strategy: "Geometric wordmark + neutral UI + mono", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 3, weight: 500, tracking: "-0.02em", leading: 1.1 },
      { role: "headline", rem: 1.375, weight: 600, leading: 1.25 },
      { role: "body", rem: 1, weight: 400, leading: 1.6 },
      { role: "mono", rem: 0.875, weight: 400, leading: 1.5 },
    ],
    tags: ["coldstart", "multi-family", "saas", "website", "latin", "free-commercial"],
    confidence: 0.9,
    verifiedBy: "human",
    summary: "SaaS stack: Space Grotesk + Inter + JetBrains Mono.",
    summaryZh: "SaaS 栈：Space Grotesk + Inter + JetBrains Mono。",
  },
  {
    id: "spec-free-poster-display-meta",
    workId: "work-free-poster-display-meta",
    typefaces: [
      { typefaceId: "playfair-display", role: "display", weight: 700 },
      { typefaceId: "work-sans", role: "headline", weight: 500 },
      { typefaceId: "work-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "High-contrast display serif + geometric meta", contrast: "high" },
    hierarchy: [
      { role: "display", rem: 4.25, weight: 700, tracking: "-0.03em", leading: 1.05 },
      { role: "headline", rem: 1.125, weight: 500, tracking: "0.04em", leading: 1.25 },
      { role: "caption", rem: 0.75, weight: 400, leading: 1.3 },
    ],
    tags: ["coldstart", "multi-family", "poster", "event", "latin", "free-commercial"],
    confidence: 0.87,
    verifiedBy: "human",
    summary: "Poster: Playfair Display + Work Sans meta.",
    summaryZh: "海报：Playfair Display + Work Sans。",
  },
  {
    id: "spec-free-gov-report",
    workId: "work-free-gov-report",
    typefaces: [
      { typefaceId: "libre-baskerville", role: "display", weight: 700 },
      { typefaceId: "libre-baskerville", role: "body", weight: 400 },
      { typefaceId: "public-sans", role: "headline", weight: 600 },
      { typefaceId: "public-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Accessible report: serif reading + civic sans", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 2.5, weight: 700, leading: 1.15 },
      { role: "headline", rem: 1.25, weight: 600, leading: 1.3 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.7 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["coldstart", "multi-family", "editorial", "government", "latin", "free-commercial"],
    confidence: 0.86,
    verifiedBy: "human",
    summary: "Gov report: Libre Baskerville + Public Sans.",
    summaryZh: "公共报告：Libre Baskerville + Public Sans。",
  },
  {
    id: "spec-free-startup-landing",
    workId: "work-free-startup-landing",
    typefaces: [
      { typefaceId: "fraunces", role: "display", weight: 600 },
      { typefaceId: "manrope", role: "headline", weight: 600 },
      { typefaceId: "ibm-plex-sans", role: "body", weight: 400 },
      { typefaceId: "ibm-plex-sans", role: "caption", weight: 400 },
    ],
    pairing: { strategy: "Soft display + geometric heads + plex body", contrast: "medium" },
    hierarchy: [
      { role: "display", rem: 3.25, weight: 600, leading: 1.1 },
      { role: "headline", rem: 1.375, weight: 600, leading: 1.25 },
      { role: "body", rem: 1.0625, weight: 400, leading: 1.65 },
      { role: "caption", rem: 0.8125, weight: 400, leading: 1.4 },
    ],
    tags: ["coldstart", "multi-family", "startup", "website", "latin", "free-commercial"],
    confidence: 0.88,
    verifiedBy: "human",
    summary: "Startup landing: Fraunces + Manrope + IBM Plex Sans.",
    summaryZh: "创业落地页：Fraunces + Manrope + IBM Plex。",
  },
];

const seedIds = new Set(RAW_SPECIMENS.map((s) => s.id));
const merged = [...RAW_SPECIMENS, ...FIU_SPECIMENS.filter((s) => !seedIds.has(s.id))];

export const SPECIMENS: readonly Specimen[] = merged.map((s) => SpecimenSchema.parse(s));
export const SPECIMEN_BY_ID: ReadonlyMap<string, Specimen> = new Map(
  SPECIMENS.map((s) => [s.id, s]),
);
