import { FIU_TYPEFACES } from "./fiu-load";
import { type Typeface, TypefaceSchema } from "./schema";

const ofl = {
  spdxOrLabel: "OFL-1.1",
  commercialOk: true as const,
  attributionRequired: false,
  redistributable: true,
  licenseUrl: "https://scripts.sil.org/OFL",
};
const RAW_TYPEFACES: Typeface[] = [
  {
    id: "inter",
    family: "Inter",
    foundry: "Rasmus Andersson",
    scripts: ["latin", "cyrillic", "greek"],
    category: "sans",
    cssStack: '"Inter", system-ui, sans-serif',
    sourceUrl: "https://rsms.me/inter/",
    license: { ...ofl },
  },
  {
    id: "source-sans-3",
    family: "Source Sans 3",
    foundry: "Adobe",
    scripts: ["latin", "cyrillic", "greek"],
    category: "sans",
    cssStack: '"Source Sans 3", system-ui, sans-serif',
    sourceUrl: "https://github.com/adobe-fonts/source-sans",
    license: { ...ofl },
  },
  {
    id: "source-serif-4",
    family: "Source Serif 4",
    foundry: "Adobe",
    scripts: ["latin", "cyrillic", "greek"],
    category: "serif",
    cssStack: '"Source Serif 4", Georgia, serif',
    sourceUrl: "https://github.com/adobe-fonts/source-serif",
    license: { ...ofl },
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    foundry: "Florian Karsten",
    scripts: ["latin"],
    category: "sans",
    cssStack: '"Space Grotesk", system-ui, sans-serif',
    sourceUrl: "https://fonts.floriankarsten.com/space-grotesk",
    license: { ...ofl },
  },
  {
    id: "dm-sans",
    family: "DM Sans",
    foundry: "Colophon / Google",
    scripts: ["latin"],
    category: "sans",
    cssStack: '"DM Sans", system-ui, sans-serif',
    sourceUrl: "https://github.com/googlefonts/dm-fonts",
    license: { ...ofl },
  },
  {
    id: "fraunces",
    family: "Fraunces",
    foundry: "Undercase Type",
    scripts: ["latin"],
    category: "display",
    cssStack: '"Fraunces", Georgia, serif',
    sourceUrl: "https://github.com/undercasetype/Fraunces",
    license: { ...ofl },
  },
  {
    id: "newsreader",
    family: "Newsreader",
    foundry: "Production Type",
    scripts: ["latin"],
    category: "serif",
    cssStack: '"Newsreader", Georgia, serif',
    sourceUrl: "https://github.com/productiontype/Newsreader",
    license: { ...ofl },
  },
  {
    id: "ibm-plex-sans",
    family: "IBM Plex Sans",
    foundry: "IBM",
    scripts: ["latin", "cyrillic", "greek"],
    category: "sans",
    cssStack: '"IBM Plex Sans", system-ui, sans-serif',
    sourceUrl: "https://github.com/IBM/plex",
    license: { ...ofl },
  },
  {
    id: "ibm-plex-serif",
    family: "IBM Plex Serif",
    foundry: "IBM",
    scripts: ["latin", "cyrillic"],
    category: "serif",
    cssStack: '"IBM Plex Serif", Georgia, serif',
    sourceUrl: "https://github.com/IBM/plex",
    license: { ...ofl },
  },
  {
    id: "jetbrains-mono",
    family: "JetBrains Mono",
    foundry: "JetBrains",
    scripts: ["latin", "cyrillic", "greek"],
    category: "mono",
    cssStack: '"JetBrains Mono", ui-monospace, monospace',
    sourceUrl: "https://www.jetbrains.com/lp/mono/",
    license: { ...ofl },
  },
  {
    id: "geist-sans",
    family: "Geist",
    foundry: "Vercel",
    scripts: ["latin"],
    category: "sans",
    cssStack: '"Geist", system-ui, sans-serif',
    sourceUrl: "https://vercel.com/font",
    license: { ...ofl },
  },
  {
    id: "geist-mono",
    family: "Geist Mono",
    foundry: "Vercel",
    scripts: ["latin"],
    category: "mono",
    cssStack: '"Geist Mono", ui-monospace, monospace',
    sourceUrl: "https://vercel.com/font",
    license: { ...ofl },
  },
  {
    id: "noto-sans-sc",
    family: "Noto Sans SC",
    foundry: "Google / Adobe",
    scripts: ["cjk-hans", "latin"],
    category: "sans",
    cssStack: '"Noto Sans SC", "PingFang SC", sans-serif',
    sourceUrl: "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
    license: { ...ofl },
  },
  {
    id: "noto-serif-sc",
    family: "Noto Serif SC",
    foundry: "Google / Adobe",
    scripts: ["cjk-hans", "latin"],
    category: "serif",
    cssStack: '"Noto Serif SC", "Songti SC", serif',
    sourceUrl: "https://fonts.google.com/noto/specimen/Noto+Serif+SC",
    license: { ...ofl },
  },
  {
    id: "source-han-sans",
    family: "Source Han Sans",
    foundry: "Adobe",
    scripts: ["cjk-hans", "cjk-hant", "cjk-jp", "cjk-kr", "latin"],
    category: "sans",
    cssStack: '"Source Han Sans", "PingFang SC", sans-serif',
    sourceUrl: "https://github.com/adobe-fonts/source-han-sans",
    license: { ...ofl },
  },
  {
    id: "source-han-serif",
    family: "Source Han Serif",
    foundry: "Adobe",
    scripts: ["cjk-hans", "cjk-hant", "cjk-jp", "cjk-kr", "latin"],
    category: "serif",
    cssStack: '"Source Han Serif", "Songti SC", serif',
    sourceUrl: "https://github.com/adobe-fonts/source-han-serif",
    license: { ...ofl },
  },
  {
    id: "lxgw-wenkai",
    family: "LXGW WenKai",
    foundry: "LXGW",
    scripts: ["cjk-hans", "latin"],
    category: "handwriting",
    cssStack: '"LXGW WenKai", "KaiTi", serif',
    sourceUrl: "https://github.com/lxgw/LxgwWenKai",
    license: { ...ofl, licenseUrl: "https://github.com/lxgw/LxgwWenKai/blob/main/OFL.txt" },
    notes: "Kai accent only.",
  },
  {
    id: "playfair-display",
    family: "Playfair Display",
    foundry: "Claus Eggers Sørensen",
    scripts: ["latin", "cyrillic"],
    category: "display",
    cssStack: '"Playfair Display", Georgia, serif',
    sourceUrl: "https://fonts.google.com/specimen/Playfair+Display",
    license: { ...ofl },
  },
  {
    id: "work-sans",
    family: "Work Sans",
    foundry: "Wei Huang",
    scripts: ["latin"],
    category: "sans",
    cssStack: '"Work Sans", system-ui, sans-serif',
    sourceUrl: "https://fonts.google.com/specimen/Work+Sans",
    license: { ...ofl },
  },
  {
    id: "libre-baskerville",
    family: "Libre Baskerville",
    foundry: "Impallari Type",
    scripts: ["latin"],
    category: "serif",
    cssStack: '"Libre Baskerville", Georgia, serif',
    sourceUrl: "https://fonts.google.com/specimen/Libre+Baskerville",
    license: { ...ofl },
  },
  {
    id: "public-sans",
    family: "Public Sans",
    foundry: "USWDS / Dan Marshall",
    scripts: ["latin"],
    category: "sans",
    cssStack: '"Public Sans", system-ui, sans-serif',
    sourceUrl: "https://public-sans.digital.gov/",
    license: { ...ofl },
  },
  {
    id: "manrope",
    family: "Manrope",
    foundry: "Mikhail Sharanda",
    scripts: ["latin", "cyrillic"],
    category: "sans",
    cssStack: '"Manrope", system-ui, sans-serif',
    sourceUrl: "https://fonts.google.com/specimen/Manrope",
    license: { ...ofl },
  },
];

const seedIds = new Set(RAW_TYPEFACES.map((t) => t.id));
const merged = [...RAW_TYPEFACES, ...FIU_TYPEFACES.filter((t) => !seedIds.has(t.id))];

export const TYPEFACES: readonly Typeface[] = merged.map((t) => TypefaceSchema.parse(t));
export const TYPEFACE_BY_ID: ReadonlyMap<string, Typeface> = new Map(
  TYPEFACES.map((t) => [t.id, t]),
);
