import { type Work, WorkSchema } from "./schema";

const RAW_WORKS: Work[] = [
  {
    id: "work-calm-saas-landing",
    slug: "calm-saas-landing",
    title: "Calm SaaS landing",
    titleZh: "冷静风 SaaS 落地页",
    medium: "website",
    industry: "saas",
    mood: ["calm", "tech", "trust"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-zh-product-site",
    slug: "zh-product-site",
    title: "Chinese product marketing site",
    titleZh: "中文产品营销站",
    medium: "website",
    industry: "saas",
    mood: ["professional", "clear", "modern"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-conference-poster",
    slug: "conference-poster",
    title: "Design conference poster",
    titleZh: "设计大会海报",
    medium: "poster",
    industry: "events",
    mood: ["expressive", "editorial", "bold"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-bilingual-brand-poster",
    slug: "bilingual-brand-poster",
    title: "Bilingual brand launch poster",
    titleZh: "中西文品牌发布海报",
    medium: "poster",
    industry: "brand",
    mood: ["warm", "premium", "cultural"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-dev-docs",
    slug: "dev-docs-shell",
    title: "Developer docs shell",
    titleZh: "开发者文档壳",
    medium: "website",
    industry: "developer-tools",
    mood: ["precise", "dense", "utilitarian"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-editorial-blog",
    slug: "editorial-blog",
    title: "Editorial product blog",
    titleZh: "产品编辑部博客",
    medium: "website",
    industry: "media",
    mood: ["literary", "calm", "longform"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-startup-pitch-poster",
    slug: "startup-pitch-poster",
    title: "Startup pitch night poster",
    titleZh: "创业路演之夜海报",
    medium: "poster",
    industry: "events",
    mood: ["energetic", "modern", "startup"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-zh-dashboard-ui",
    slug: "zh-dashboard-ui",
    title: "Chinese SaaS dashboard UI",
    titleZh: "中文 SaaS 控制台 UI",
    medium: "app-ui",
    industry: "saas",
    mood: ["dense", "neutral", "operational"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
];
export const WORKS: readonly Work[] = RAW_WORKS.map((w) => WorkSchema.parse(w));
export const WORK_BY_ID: ReadonlyMap<string, Work> = new Map(WORKS.map((w) => [w.id, w]));
export const WORK_BY_SLUG: ReadonlyMap<string, Work> = new Map(WORKS.map((w) => [w.slug, w]));
