import { FIU_WORKS } from "./fiu-load";
import { type Work, WorkSchema } from "./schema";

const RAW_WORKS: Work[] = [
  {
    id: "work-calm-saas-landing",
    slug: "calm-saas-landing",
    title: "Calm SaaS landing",
    titleZh: "冷静风 SaaS 落地页",
    medium: "website",
    industry: "saas",
    mood: ["calm", "tech", "trust"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-zh-product-site",
    slug: "zh-product-site",
    title: "Chinese product marketing site",
    titleZh: "中文产品营销站",
    medium: "website",
    industry: "saas",
    mood: ["professional", "clear", "modern"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-conference-poster",
    slug: "conference-poster",
    title: "Design conference poster",
    titleZh: "设计大会海报",
    medium: "poster",
    industry: "events",
    mood: ["expressive", "editorial", "bold"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-bilingual-brand-poster",
    slug: "bilingual-brand-poster",
    title: "Bilingual brand launch poster",
    titleZh: "中西文品牌发布海报",
    medium: "poster",
    industry: "brand",
    mood: ["warm", "premium", "cultural"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-dev-docs",
    slug: "dev-docs-shell",
    title: "Developer docs shell",
    titleZh: "开发者文档壳",
    medium: "website",
    industry: "developer-tools",
    mood: ["precise", "dense", "utilitarian"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-editorial-blog",
    slug: "editorial-blog",
    title: "Editorial product blog",
    titleZh: "产品编辑部博客",
    medium: "website",
    industry: "media",
    mood: ["literary", "calm", "longform"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-startup-pitch-poster",
    slug: "startup-pitch-poster",
    title: "Startup pitch night poster",
    titleZh: "创业路演之夜海报",
    medium: "poster",
    industry: "events",
    mood: ["energetic", "modern", "startup"],
    scripts: ["latin"],
    imageAssets: [],
    status: "published",
  },
  {
    id: "work-zh-dashboard-ui",
    slug: "zh-dashboard-ui",
    title: "Chinese SaaS dashboard UI",
    titleZh: "中文 SaaS 控制台 UI",
    medium: "app-ui",
    industry: "saas",
    mood: ["dense", "neutral", "operational"],
    scripts: ["cjk-hans", "latin"],
    imageAssets: [],
    status: "published",
  },
  // --- FIU metadata cold-start (free commercial faces only; prose rewritten) ---
  {
    id: "work-fiu-vercel-website",
    slug: "fiu-vercel-website",
    title: "Vercel product website",
    titleZh: "Vercel 产品站",
    medium: "website",
    industry: "developer-tools",
    mood: ["tight-letterspacing", "variable-fonts", "brands", "websites"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/35337/vercel-website",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-fiu-vksplan-website",
    slug: "fiu-vksplan-website",
    title: "VKSplan website",
    medium: "website",
    mood: ["websites"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/73687/vksplan-website",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-fiu-taylor-roy-portfolio",
    slug: "fiu-taylor-roy-portfolio",
    title: "Taylor Roy portfolio website",
    medium: "website",
    mood: ["portfolios", "websites"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/77391/taylor-roy-portfolio-website",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-fiu-northmed-identity",
    slug: "fiu-northmed-identity",
    title: "NorthMed visual identity",
    medium: "brand-identity",
    industry: "brand",
    mood: ["brands", "healthcare"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/66227/northmed-visual-identity",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-fiu-bel-canto",
    slug: "fiu-bel-canto",
    title: "Shaping the Future of Bel Canto",
    medium: "editorial",
    mood: ["editorial", "music"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/77514/shaping-the-future-of-bel-canto",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-fiu-we-are-water",
    slug: "fiu-we-are-water",
    title: "We Are Water Foundation activity report",
    medium: "editorial",
    mood: ["reports", "editorial"],
    scripts: ["latin"],
    sourceUrl: "https://fontsinuse.com/uses/63895/we-are-water-foundation-2020-2023-activity-re",
    imageAssets: [],
    curatorNotes:
      "Cold-start from Fonts In Use public metadata. Free faces only; not a republication of FIU prose/images.",
    status: "published",
  },
  {
    id: "work-free-editorial-serif-sans",
    slug: "free-editorial-serif-sans",
    title: "Open editorial: serif story + sans chrome",
    titleZh: "开放编辑：衬线正文 + 无衬线壳",
    medium: "website",
    industry: "media",
    mood: ["literary", "longform", "calm"],
    scripts: ["latin"],
    imageAssets: [],
    curatorNotes: "Curated free-commercial pairing for cold-start (Newsreader + Public Sans).",
    status: "published",
  },
  {
    id: "work-free-saas-grotesk-stack",
    slug: "free-saas-grotesk-stack",
    title: "SaaS stack: geometric wordmark + UI sans",
    titleZh: "SaaS 栈：几何字标 + UI 无衬线",
    medium: "website",
    industry: "saas",
    mood: ["modern", "product", "trust"],
    scripts: ["latin"],
    imageAssets: [],
    curatorNotes: "Curated free-commercial pairing (Space Grotesk + Inter + JetBrains Mono).",
    status: "published",
  },
  {
    id: "work-free-poster-display-meta",
    slug: "free-poster-display-meta",
    title: "Poster system: display serif + meta sans",
    titleZh: "海报系统：展示衬线 + 元信息无衬线",
    medium: "poster",
    industry: "events",
    mood: ["expressive", "high-contrast", "editorial"],
    scripts: ["latin"],
    imageAssets: [],
    curatorNotes: "Curated free-commercial pairing (Playfair Display + Work Sans).",
    status: "published",
  },
  {
    id: "work-free-gov-report",
    slug: "free-gov-report",
    title: "Public-sector report system",
    titleZh: "公共部门报告系统",
    medium: "editorial",
    industry: "government",
    mood: ["clear", "neutral", "accessible"],
    scripts: ["latin"],
    imageAssets: [],
    curatorNotes: "Curated free-commercial pairing (Public Sans + Libre Baskerville).",
    status: "published",
  },
  {
    id: "work-free-startup-landing",
    slug: "free-startup-landing",
    title: "Startup landing: soft display + plex body",
    titleZh: "创业落地页：柔和展示 + Plex 正文",
    medium: "website",
    industry: "startup",
    mood: ["friendly", "product", "energetic"],
    scripts: ["latin"],
    imageAssets: [],
    curatorNotes: "Curated free-commercial pairing (Fraunces + IBM Plex Sans + Manrope).",
    status: "published",
  },
];

const seedIds = new Set(RAW_WORKS.map((w) => w.id));
const merged = [...RAW_WORKS, ...FIU_WORKS.filter((w) => !seedIds.has(w.id))];

export const WORKS: readonly Work[] = merged.map((w) => WorkSchema.parse(w));
export const WORK_BY_ID: ReadonlyMap<string, Work> = new Map(WORKS.map((w) => [w.id, w]));
export const WORK_BY_SLUG: ReadonlyMap<string, Work> = new Map(WORKS.map((w) => [w.slug, w]));
