import { ROUTE_LASTMOD } from "./route-lastmod.generated";
import { resolveSeoRoute } from "./route-registry";

/**
 * `<lastmod>` for a route, from mechanical sources only.
 *
 * Priority:
 *   1. `contentDate` — a real content timestamp (Sanity `_updatedAt`, blog
 *      `post.date`, a release date). This is the most honest signal available.
 *   2. `ROUTE_LASTMOD` — git commit time of the page + data modules that render
 *      the route's registry pattern, generated by `pnpm gen:route-lastmod`.
 *   3. `undefined` — omit the field.
 *
 * Returning `undefined` is deliberate. `new Date()` must NEVER appear in a
 * sitemap module: a build-time-uniform lastmod tells crawlers every URL changed
 * at once, which is the exact pattern they classify as untrustworthy and
 * discard. An omitted `<lastmod>` is honest; a fabricated one is worse than
 * absent.
 */
export function lastModifiedFor(
  path: string,
  contentDate?: Date | null | string,
): Date | undefined {
  const fromContent = toValidDate(contentDate);
  if (fromContent) return fromContent;

  const entry = resolveSeoRoute(path);
  if (!entry) return undefined;

  return toValidDate(ROUTE_LASTMOD[entry.pattern]);
}

/**
 * A date is only usable as `<lastmod>` if it is a real timestamp. The Unix
 * epoch is not: `@/lib/blog` synthesizes `new Date(0)` for a post with neither
 * `publishedAt` nor `_updatedAt`, and a 1970 `<lastmod>` is a fabricated date
 * in the opposite direction from `new Date()` — equally untrustworthy, and it
 * slips past a guard that only rejects timestamps in the future. Anything at or
 * before the epoch is a sentinel, so it is dropped and the field is omitted.
 */
function toValidDate(value: Date | null | string | undefined): Date | undefined {
  if (!value) return undefined;
  const date = value instanceof Date ? value : new Date(value);
  const time = date.getTime();
  return Number.isNaN(time) || time <= 0 ? undefined : date;
}
