/**
 * AUTO-GENERATED by scripts/generate-route-lastmod.mjs — do not hand-edit.
 * Source of truth: git commit time of the page + data modules that render each
 * pattern in apps/landing/src/lib/seo/route-registry.ts.
 * Regenerate with: pnpm gen:route-lastmod
 */
export const ROUTE_LASTMOD: Record<string, string> = {
  "/": "2026-07-24T16:43:02+08:00",
  "/about": "2026-07-26T00:44:54+08:00",
  "/about/products": "2026-07-24T16:43:02+08:00",
  "/ai/models": "2026-07-26T00:44:54+08:00",
  "/blog": "2026-07-26T00:44:54+08:00",
  "/blog/*": "2026-07-26T00:44:54+08:00",
  "/careers": "2026-07-24T16:43:02+08:00",
  "/changelog": "2026-07-24T16:43:02+08:00",
  "/changelog/*": "2026-07-26T00:44:54+08:00",
  "/contact": "2026-07-24T16:45:21+08:00",
  "/cookies": "2026-07-24T16:45:21+08:00",
  "/dpa": "2026-07-24T16:45:21+08:00",
  "/faq": "2026-07-24T16:45:21+08:00",
  "/features": "2026-07-26T00:44:54+08:00",
  "/features/*": "2026-07-26T00:44:54+08:00",
  "/get-license": "2026-07-24T16:43:02+08:00",
  "/ideas": "2026-07-24T16:43:02+08:00",
  "/licensing": "2026-07-24T16:43:02+08:00",
  "/news": "2026-07-26T00:44:54+08:00",
  "/pricing": "2026-07-24T16:43:02+08:00",
  "/privacy": "2026-07-24T16:45:21+08:00",
  "/refer": "2026-07-24T16:43:02+08:00",
  "/refund": "2026-07-24T16:45:21+08:00",
  "/roadmap": "2026-07-24T16:43:02+08:00",
  "/security": "2026-07-24T16:43:02+08:00",
  "/solutions": "2026-07-26T00:44:54+08:00",
  "/solutions/*": "2026-07-26T00:44:54+08:00",
  "/status": "2026-07-24T16:43:02+08:00",
  "/terms": "2026-07-24T16:45:21+08:00",
};
