export const legacyNextBoundaryInventory = {
  apiRouteHandlers: {
    authAndAccount: [
      "/api/auth/[...all]",
      "/api/auth/current-session",
      "/api/auth/desktop/exchange",
      "/api/auth/desktop/me",
      "/api/auth/google-one-tap",
      "/api/auth/list-accounts",
      "/api/auth/list-sessions",
      "/api/auth/passkey/rename",
      "/api/auth/revoke-other-sessions",
      "/api/auth/revoke-session",
      "/api/auth/sso/discovery",
      "/api/auth/two-factor-status",
      "/api/account",
      "/api/account/avatar",
      "/api/account/email-change",
      "/api/account/email-change/[token]",
      "/api/account/export",
    ],
    tenantWorkspacePermissions: [
      "/api/organizations",
      "/api/organizations/active",
      "/api/organizations/[orgId]",
      "/api/organizations/[orgId]/members",
      "/api/organizations/[orgId]/members/[memberId]",
      "/api/organizations/[orgId]/threads",
      "/api/admin/access-invites",
      "/api/admin/directory",
      "/api/admin/impersonate",
      "/api/admin/organizations/[orgId]",
      "/api/admin/users/[userId]",
      "/api/invitations/[invitationId]/accept",
      "/api/invitations/[invitationId]/decline",
      "/api/onboarding/invite-members",
    ],
    productMutations: [
      "/api/api-keys",
      "/api/api-keys/[id]",
      "/api/provider-keys",
      "/api/provider-keys/[provider]",
      "/api/notifications",
      "/api/notifications/[id]",
      "/api/notifications/inbox",
      "/api/notifications/preferences",
      "/api/audit-logs",
      "/api/billing/active-plan",
      "/api/billing/checkout",
      "/api/billing/credits/summary",
      "/api/billing/portal",
      "/api/cofounder/discover",
      "/api/cofounder/interest",
      "/api/cofounder/matches",
      "/api/cofounder/opt-in",
      "/api/cofounder/room/[profileId]",
      "/api/cofounder/room/[profileId]/form-team",
      "/api/feedback",
      "/api/growth/summary",
      "/api/me/profile",
      "/api/me/public",
    ],
    agentRuntimeAndArtifacts: ["/api/atelier/generate", "/api/reel/run"],
    uploadWebhookCronAndPublicRead: [
      "/api/uploads/[...key]",
      "/api/organizations/[orgId]/logo",
      "/api/organizations/[orgId]/logo-upload-url",
      "/api/organizations/[orgId]/logo-url",
      "/api/webhooks",
      "/api/webhooks/[id]",
      "/api/webhooks/[id]/deliveries",
      "/api/webhooks/queuebase",
      "/api/cron/invitation-cleanup",
      "/api/cron/session-cleanup",
      "/api/blog/comments",
      "/api/blog/reactions",
      "/api/cookie-consent",
      "/api/e2e/health",
    ],
  },
  serverActions: [
    "src/app/(app)/settings/api-keys/actions.ts",
    "src/app/(app)/settings/notifications/actions.ts",
    "src/app/(app)/settings/team/actions.ts",
  ],
  authServerHelpers: [
    "src/lib/auth.ts",
    "src/proxy.ts",
    "src/app/api/auth/[...all]/route.ts",
    "src/app/login/remote/route.ts",
    "src/app/signup/remote/route.ts",
  ],
  serverOnlyUtilities: [
    "src/lib/db.ts",
    "src/lib/warehouse/gold.ts",
    "src/lib/logo-url.ts",
    "src/lib/cofounder/context.ts",
    "src/lib/cofounder/team-provisioning.ts",
    "src/lib/invitations.ts",
    "src/lib/startup-os/conversation.ts",
    "src/lib/startup-os/execution.ts",
    "src/lib/startup-os/company-context/generate.ts",
  ],
  disposition: {
    alreadyGatewayOwned: [
      "billing credits and usage under backends/gateway/src/routes/billing",
      "notifications under backends/gateway/src/routes/notifications",
      "uploads under backends/gateway/src/routes/uploads",
      "webhooks under backends/gateway/src/routes/webhooks",
      "agent-runtime and workflows under backends/gateway/src/routes/agent-runtime and workflows",
      "AI provider keys under backends/gateway/src/routes/ai/provider-keys",
      "Startup OS projects/detail/files/canvas/context/review/revert/chat/run execute under backends/gateway/src/routes/startup-os",
    ],
    mustMoveBeforeDeletingLegacyNext: [
      "organization membership and active organization handlers",
      "account profile/avatar/email-change/export handlers",
      "auth session/passkey/session-management handlers",
      "settings server actions for api keys, notifications, and team membership",
      "cron cleanup handlers and blog reaction/comment handlers",
    ],
  },
} as const;
