export {
  checkEntitlement,
  checkEntitlementUsage,
  type Entitlement,
  type EntitlementCheckResult,
  FEATURES,
  type FeatureKey,
  type GrantEntitlementInput,
  getEntitlements,
  grantEntitlement,
  incrementUsage,
  initializePlanEntitlements,
  isPlanFeature,
  METER_TO_PLAN_LIMIT,
  PLAN_FEATURES,
  requireEntitlement,
  requireEntitlementUsage,
  resetUsage,
  revokeEntitlement,
  type UsageEntitlementResult,
} from "./service";
