/**
 * AUTO-GENERATED by scripts/sync-languages.mjs — DO NOT EDIT.
 * Built-in Brand Packages for applyLanguage(id) without manual JSON import.
 * Source: packages/design/tokens/brands/<id>/brand.json
 */

import { type BrandPackage, normalizeBrandPackage } from "@nebutra/tokens/brand-package";
import cosmos from "@nebutra/tokens/brands/cosmos/brand.json" with { type: "json" };
import gsap from "@nebutra/tokens/brands/gsap/brand.json" with { type: "json" };
import linear from "@nebutra/tokens/brands/linear/brand.json" with { type: "json" };
import notion from "@nebutra/tokens/brands/notion/brand.json" with { type: "json" };
import raycast from "@nebutra/tokens/brands/raycast/brand.json" with { type: "json" };
import stripe from "@nebutra/tokens/brands/stripe/brand.json" with { type: "json" };
import vanta from "@nebutra/tokens/brands/vanta/brand.json" with { type: "json" };
import vercel from "@nebutra/tokens/brands/vercel/brand.json" with { type: "json" };

const RAW_BUILT_IN: Record<string, BrandPackage> = {
  cosmos: cosmos as BrandPackage,
  gsap: gsap as BrandPackage,
  linear: linear as BrandPackage,
  notion: notion as BrandPackage,
  raycast: raycast as BrandPackage,
  stripe: stripe as BrandPackage,
  vanta: vanta as BrandPackage,
  vercel: vercel as BrandPackage,
};

/** Normalized package for a shipped design-language id, or undefined. */
export function getBuiltInBrandPackage(id: string): BrandPackage | undefined {
  const raw = RAW_BUILT_IN[id];
  if (!raw) return undefined;
  return normalizeBrandPackage({ ...raw, id });
}

export function listBuiltInBrandIds(): string[] {
  return Object.keys(RAW_BUILT_IN);
}

export function hasBuiltInBrandPackage(id: string): boolean {
  return id in RAW_BUILT_IN;
}
