#!/usr/bin/env tsx

/**
 * Brand Apply Script
 *
 * Applies brand.config.ts settings throughout the codebase.
 * Run with: pnpm brand:apply
 */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { type BrandConfig, DEFAULT_BRAND } from "./brand-types";

// `import.meta.dirname` is unset under tsx CJS transform on Node 25.
// Compute it from `import.meta.url` for cross-runtime compatibility.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// ANSI colors
const _c = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
};

function logStep(_step: string) {}

function logSuccess(_message: string) {}

function logSkip(_message: string) {}

function _logError(_message: string) {}

/**
 * Load brand config or use defaults
 */
async function loadConfig(): Promise<BrandConfig> {
  const configPath = path.join(ROOT, "brand.config.ts");

  if (!fs.existsSync(configPath)) {
    return DEFAULT_BRAND;
  }

  try {
    // Dynamic import of the config
    const configModule = await import(configPath);
    return configModule.default as BrandConfig;
  } catch (_error) {
    process.exit(1);
  }
}

/**
 * Replace all occurrences in a file
 */
function replaceInFile(filePath: string, replacements: Array<[string | RegExp, string]>): boolean {
  if (!fs.existsSync(filePath)) return false;

  let content = fs.readFileSync(filePath, "utf-8");
  let modified = false;

  for (const [search, replace] of replacements) {
    const newContent = content.replace(search, replace);
    if (newContent !== content) {
      content = newContent;
      modified = true;
    }
  }

  if (modified) {
    fs.writeFileSync(filePath, content, "utf-8");
  }

  return modified;
}

/**
 * Copy custom assets if they exist
 */
function copyCustomAssets(_config: BrandConfig): void {
  logStep("Copying custom assets");

  const customAssetsDir = path.join(ROOT, "brand.config", "assets");
  const targetAssetsDir = path.join(ROOT, "packages", "brand", "assets");

  if (!fs.existsSync(customAssetsDir)) {
    logSkip("No custom assets found in brand.config/assets/");
    return;
  }

  // Copy logo files
  const logoDir = path.join(customAssetsDir, "logo");
  if (fs.existsSync(logoDir)) {
    const targetLogoDir = path.join(targetAssetsDir, "logo");
    const files = fs.readdirSync(logoDir);
    for (const file of files) {
      fs.copyFileSync(path.join(logoDir, file), path.join(targetLogoDir, file));
      logSuccess(`Copied logo/${file}`);
    }
  }

  // Copy favicon files
  const faviconDir = path.join(customAssetsDir, "favicon");
  if (fs.existsSync(faviconDir)) {
    const targetFaviconDir = path.join(targetAssetsDir, "favicon");
    const files = fs.readdirSync(faviconDir);
    for (const file of files) {
      fs.copyFileSync(path.join(faviconDir, file), path.join(targetFaviconDir, file));
      logSuccess(`Copied favicon/${file}`);
    }
  }
}

/**
 * Update packages/design/brand/src/metadata.ts
 */
function updateBrandMetadata(config: BrandConfig): void {
  logStep("Updating brand metadata");

  // brand package moved under packages/design/ in the 2026-05 categorized
  // layout — keep the path in sync with the actual workspace location.
  const metadataPath = path.join(ROOT, "packages", "design", "brand", "src", "metadata.ts");

  // Serialize a nested object literal as a TS `as const` block. We use
  // JSON.stringify for structural correctness then strip the outer-key
  // quotes so the output looks idiomatic; Biome runs after to handle
  // trailing commas / blank-line whitespace.
  const serialize = (value: unknown): string => {
    return JSON.stringify(value, null, 2);
  };

  const story = config.brand.story;
  const storyBlock = story
    ? `  story: {
    concept: ${JSON.stringify(story.concept)},
    colorMeaning: ${JSON.stringify(story.colorMeaning)},
    values: ${JSON.stringify(story.values)},
    missionStatement: ${JSON.stringify(story.missionStatement)},
  },\n\n`
    : "";

  const newContent = `/**
 * ${config.brand.name} Brand Metadata
 * Central source of truth for brand identity
 *
 * AUTO-GENERATED by \`pnpm brand:apply\` from \`scripts/brand-types.ts\`
 * (DEFAULT_BRAND) or a sibling \`brand.config.ts\` if present. Do NOT
 * edit by hand — your edits will be wiped on the next brand:apply.
 *
 * To rebrand, edit DEFAULT_BRAND in scripts/brand-types.ts and run
 * \`pnpm brand:apply\`. To extend the shape, add a field to BrandConfig,
 * set its value in DEFAULT_BRAND, then read it from this writer.
 *
 * Pipeline guard: tests/architecture/brand-metadata-drift.test.ts
 * asserts \`metadata.ts\` is byte-identical to what brand:apply emits.
 */

export const brand = {
  name: ${JSON.stringify(config.brand.name)},
  nameCn: ${JSON.stringify(config.brand.nameCn ?? config.brand.name)},
  nameFull: ${JSON.stringify(config.brand.nameFull ?? config.company.name)},
  nameFullEn: ${JSON.stringify(config.brand.nameFullEn ?? config.company.name)},

  tagline: ${JSON.stringify(config.brand.tagline)},
  taglineCn: ${JSON.stringify(config.brand.taglineCn ?? config.brand.tagline)},
  description: ${JSON.stringify(config.brand.description)},
  descriptionCn: ${JSON.stringify(config.brand.descriptionCn ?? config.brand.description)},

${storyBlock}  domains: ${serialize(config.domains)},

  social: ${serialize({
    twitter: config.social.twitter ?? "",
    github: config.social.github ?? "",
    discord: config.social.discord ?? "",
    linkedin: config.social.linkedin ?? "",
  })},
} as const;

/**
 * Brand Colors — full VI palette + brand gradients + semantic colors.
 * Aligned with @nebutra/design-tokens DTCG SSOT (tokens/core.json).
 */
export const colors = ${serialize(config.colors)} as const;

/**
 * Typography — "Precision Stack" (Geist + Noto Sans SC + Geist Mono).
 */
export const typography = ${serialize(config.typography)} as const;

/**
 * Logo asset paths (relative to package), dual-edition structure:
 *   - classic (v1.0): preferred for UX / product surfaces
 *   - compliant (v2.0): required for commercial / legal contexts
 */
export const logoAssets = ${serialize(config.logoAssets)} as const;

/**
 * Font asset paths (relative to package).
 */
export const fontAssets = ${serialize(config.fontAssets)} as const;

/**
 * Favicon assets.
 */
export const faviconAssets = ${serialize(config.faviconAssets)} as const;

/**
 * OG Image dimensions.
 */
export const ogImageDimensions = ${serialize(config.ogImageDimensions)} as const;

export type BrandColors = typeof colors;
export type BrandTypography = typeof typography;
export type LogoAssets = typeof logoAssets;
`;

  fs.writeFileSync(metadataPath, newContent, "utf-8");

  // JSON.stringify produces quoted object keys ("primary": instead of
  // primary:) and no trailing commas — Biome's strict mode rejects both.
  // Auto-fix the just-emitted file so brand:apply always lands a
  // lint-clean tree (otherwise `pnpm lint` in CI flags the generator's
  // own output, which kept CI red across runs 26079161015 → 26081453758).
  try {
    execFileSync(
      "pnpm",
      ["exec", "biome", "check", "--write", "--no-errors-on-unmatched", metadataPath],
      { cwd: ROOT, stdio: "pipe" },
    );
  } catch {
    // Biome exits non-zero when it can't auto-fix every diagnostic; the
    // file is still written with whatever fixes did apply, and the CI
    // lint job will surface anything that survived.
  }

  logSuccess("Updated packages/design/brand/src/metadata.ts");
}

/**
 * Update package.json files with new scope
 */
function updatePackageScopes(config: BrandConfig): void {
  logStep("Updating package scopes");

  const oldScope = "@nebutra";
  const newScope = config.packageScope;

  if (oldScope === newScope) {
    logSkip("Package scope unchanged");
    return;
  }

  // Find all package.json files
  const packagesDir = path.join(ROOT, "packages");
  const appsDir = path.join(ROOT, "apps");

  const packageDirs = [
    ...fs.readdirSync(packagesDir).map((d) => path.join(packagesDir, d)),
    ...fs.readdirSync(appsDir).map((d) => path.join(appsDir, d)),
  ];

  for (const dir of packageDirs) {
    const pkgPath = path.join(dir, "package.json");
    if (!fs.existsSync(pkgPath)) continue;

    const content = fs.readFileSync(pkgPath, "utf-8");
    const newContent = content.replace(new RegExp(oldScope, "g"), newScope);

    if (content !== newContent) {
      fs.writeFileSync(pkgPath, newContent, "utf-8");
      logSuccess(`Updated ${path.relative(ROOT, pkgPath)}`);
    }
  }

  // Update root package.json
  const rootPkgPath = path.join(ROOT, "package.json");
  replaceInFile(rootPkgPath, [[new RegExp(oldScope, "g"), newScope]]);
}

/**
 * Update README files from templates
 */
function updateREADMEs(config: BrandConfig): void {
  logStep("Updating README files");

  const templates = [
    { template: "README.template.md", output: "README.md" },
    { template: "README.zh-CN.template.md", output: "README.zh-CN.md" },
    // Japanese was orphan-edited for ~6 months — wire it back into the
    // pipeline so future brand:apply runs keep all three READMEs aligned.
    { template: "README.ja.template.md", output: "README.ja.md" },
  ];

  for (const { template, output } of templates) {
    const templatePath = path.join(ROOT, template);
    const outputPath = path.join(ROOT, output);

    if (!fs.existsSync(templatePath)) {
      logSkip(`Template ${template} not found`);
      continue;
    }

    let content = fs.readFileSync(templatePath, "utf-8");

    // Replace placeholders
    const replacements: Record<string, string> = {
      "{{brand.name}}": config.brand.name,
      "{{brand.tagline}}": config.brand.tagline,
      "{{brand.description}}": config.brand.description,
      "{{company.name}}": config.company.name,
      "{{company.nameCN}}": config.company.nameCN || config.company.name,
      "{{company.email}}": config.company.email,
      "{{company.year}}": String(config.company.year),
      "{{domains.landing}}": config.domains.landing,
      "{{domains.app}}": config.domains.app,
      "{{domains.api}}": config.domains.api,
      "{{repo.owner}}": config.repo.owner,
      "{{repo.name}}": config.repo.name,
      "{{repo.full}}": `${config.repo.owner}/${config.repo.name}`,
      "{{social.twitter}}": config.social.twitter || "",
      "{{social.github}}": config.social.github || "",
      "{{social.discord}}": config.social.discord || "",
      "{{colors.primary.500}}": config.colors.primary[500],
      "{{colors.accent.500}}": config.colors.accent[500],
      "{{packageScope}}": config.packageScope,
    };

    for (const [placeholder, value] of Object.entries(replacements)) {
      content = content.replace(new RegExp(placeholder.replace(/[{}]/g, "\\$&"), "g"), value);
    }

    // Handle vision pillars
    if (config.brand.vision?.pillars) {
      const visionList = config.brand.vision.pillars
        .map((p) => `- ${p.word}: ${p.meaning}`)
        .join("\n");
      content = content.replace("{{brand.vision}}", visionList);
    }

    // Handle license exemptions
    const exemptList = config.license.commercialExempt.join(", ");
    content = content.replace("{{license.commercialExempt}}", exemptList);

    fs.writeFileSync(outputPath, content, "utf-8");
    logSuccess(`Generated ${output}`);
  }
}

/**
 * Update environment variables template
 */
function updateEnvTemplate(config: BrandConfig): void {
  logStep("Updating .env.example");

  const envPath = path.join(ROOT, ".env.example");
  if (!fs.existsSync(envPath)) {
    logSkip(".env.example not found");
    return;
  }

  const replacements: Array<[RegExp, string]> = [
    [/NEXT_PUBLIC_APP_URL=.*/g, `NEXT_PUBLIC_APP_URL=https://${config.domains.app}`],
    [/NEXT_PUBLIC_API_URL=.*/g, `NEXT_PUBLIC_API_URL=https://${config.domains.api}`],
  ];

  if (replaceInFile(envPath, replacements)) {
    logSuccess("Updated .env.example");
  } else {
    logSkip("No changes needed");
  }
}

/**
 * Main
 */
async function main() {
  const config = await loadConfig();

  // Apply changes
  copyCustomAssets(config);
  updateBrandMetadata(config);
  updatePackageScopes(config);
  updateREADMEs(config);
  updateEnvTemplate(config);
}

main().catch(console.error);
