#!/usr/bin/env node
/**
 * generate-palette.mjs
 *
 * Derives the two brand scales (11 steps each) from two hex colours and prints
 * them as the `colors.primary` / `colors.accent` block of brand.config.ts.
 * No dependencies — pure Node.js.
 *
 * The scales are the colour SEED, not an override: paste them into
 * brand.config.ts and run `pnpm brand:apply`, which writes them into the token
 * source (design-tokens core.json) and regenerates styles.css, the brand VI
 * metadata and @nebutra/tokens/values from there. There is no second layer to
 * import on top — this used to print a brand-override.css that redeclared the
 * scale (and a multi-stop --brand-gradient the tokens no longer have) after
 * the stylesheet, which is how a rebrand drifted from its own source.
 *
 * Usage:
 *   node scripts/generate-palette.mjs --primary=#7C3AED --secondary=#F59E0B
 */

// ── Argument parsing ────────────────────────────────────────

const args = Object.fromEntries(
  process.argv.slice(2).map((arg) => {
    const [key, value] = arg.replace(/^--/, "").split("=");
    return [key, value];
  }),
);

const primary = args.primary ?? "#0033FE";
const secondary = args.secondary ?? "#0BF1C3";

if (!primary.match(/^#[0-9A-Fa-f]{6}$/) || !secondary.match(/^#[0-9A-Fa-f]{6}$/)) {
  process.exit(1);
}

// ── Color math ──────────────────────────────────────────────

function hexToHsl(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0,
    s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      case b:
        h = ((r - g) / d + 4) / 6;
        break;
    }
  }
  return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

function hslToHex(h, s, l) {
  const sN = s / 100,
    lN = l / 100;
  const a = sN * Math.min(lN, 1 - lN);
  const f = (n) => {
    const k = (n + h / 30) % 12;
    const color = lN - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color)
      .toString(16)
      .padStart(2, "0");
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/**
 * Generate an 11-step scale from a base color.
 * Steps: 50, 100, 200, 300, 400, 500 (base), 600, 700, 800, 900, 950
 */
function generateScale(hex) {
  const [h, s, l] = hexToHsl(hex);
  // Lightness values for each step (50→950)
  const lightnesses = [
    97,
    93,
    85,
    75,
    62,
    l,
    Math.max(l - 10, 5),
    Math.max(l - 20, 3),
    Math.max(l - 30, 2),
    Math.max(l - 40, 1),
    Math.max(l - 50, 0),
  ];
  const steps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  return Object.fromEntries(
    steps.map((step, i) => [step, hslToHex(h, Math.min(s, 95), Math.max(lightnesses[i], 1))]),
  );
}

// ── Generate ────────────────────────────────────────────────

const primaryScale = generateScale(primary);
const secondaryScale = generateScale(secondary);

const block = (name, source, scale) =>
  `    ${name}: {\n${Object.entries(scale)
    .map(([step, hex]) => `      ${step}: "${hex}",${step === "500" ? ` // ${source}` : ""}`)
    .join("\n")}\n    },`;

const output = `// brand.config.ts → colors — generated by scripts/generate-palette.mjs
// from primary ${primary} and accent ${secondary}. Paste into your config's
// \`colors\`, then run \`pnpm brand:apply\`.
  colors: {
${block("primary", primary, primaryScale)}
${block("accent", secondary, secondaryScale)}
  },
`;

process.stdout.write(output);
