/**
 * Build skins.css — multi-language catalog for html[data-brand] switching.
 *
 * Reads tokens/skins/*.css (global emit), rewrites selectors to scoped-only,
 * concatenates into packages/design/theme/skins.css.
 *
 * Product chrome SSOT remains tokens/styles.css; this file never paints :root alone.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { formatGenerated } from "../../tokens/scripts/format-generated.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageRoot, "../../..");
const tokensRoot = resolve(packageRoot, "..", "tokens");
const skinsDir = join(tokensRoot, "skins");
const outPath = join(packageRoot, "skins.css");

if (!existsSync(skinsDir)) {
  throw new Error(`Missing skins dir at ${skinsDir}`);
}

/** Keep only html[data-brand] activation — strip global :root / optional .dark binding. */
function toScopedCatalogCss(css, id) {
  const scoped = `html[data-brand="${id}"] {`;
  const out = css
    // darkDefault=true global: ":root,\n.dark,\nhtml[data-brand=\"id\"] {"
    .replace(/:root\s*,\s*\n\.dark\s*,\s*\nhtml\[data-brand="[^"]+"\]\s*\{/g, scoped)
    .replace(/:root\s*,\s*\.dark\s*,\s*html\[data-brand="[^"]+"\]\s*\{/g, scoped)
    // darkDefault=false global: ":root,\nhtml[data-brand=\"id\"] {" (no .dark)
    .replace(/:root\s*,\s*\nhtml\[data-brand="[^"]+"\]\s*\{/g, scoped)
    .replace(/:root\s*,\s*html\[data-brand="[^"]+"\]\s*\{/g, scoped);

  // Safety: never leave a bare :root { color block from a skin
  if (/^:root\s*\{/m.test(out) || /\n:root\s*,/.test(out)) {
    throw new Error(`Skin ${id} still binds :root after scoping — fix emit or regex`);
  }
  return out.trimEnd();
}

const files = readdirSync(skinsDir)
  .filter((f) => f.endsWith(".css") && f !== "README.md")
  .sort();

const ids = [];
const chunks = [
  "/**",
  " * @nebutra/theme — skins.css (design-language catalog)",
  " * AUTO-GENERATED by scripts/sync-skins.mjs — DO NOT EDIT.",
  " *",
  " * Product chrome SSOT: @nebutra/tokens/styles.css + recipe.css",
  " * This file: scoped Brand Package skins under html[data-brand] only.",
  ' * Switch: document.documentElement.dataset.brand = "vanta" | "linear" | ...',
  ' * Factory: delete dataset.brand (or clearLanguage() / applyLanguage("factory")).',
  " *",
  ` * Languages: ${files.map((f) => f.replace(/\.css$/, "")).join(", ")}`,
  " */",
  "",
];

for (const file of files) {
  const id = file.replace(/\.css$/, "");
  const raw = readFileSync(join(skinsDir, file), "utf8");
  ids.push(id);
  chunks.push(toScopedCatalogCss(raw, id));
  chunks.push("");
}

writeFileSync(outPath, `${chunks.join("\n").trimEnd()}\n`);
formatGenerated(outPath);
process.stdout.write(`skins.css refreshed: ${ids.length} languages -> ${outPath}\n`);
