/**
 * Build skins.css — multi-language catalog for html[data-brand] switching.
 *
 * Reads tokens/skins/*.css (global emit), rewrites selectors to scoped-only,
 * concatenates into packages/design/theme/skins.css.
 *
 * Product chrome SSOT remains tokens/styles.css; this file never paints :root alone.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { formatGenerated } from "../../tokens/scripts/format-generated.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageRoot, "../../..");
const tokensRoot = resolve(packageRoot, "..", "tokens");
const skinsDir = join(tokensRoot, "skins");
const outPath = join(packageRoot, "skins.css");

if (!existsSync(skinsDir)) {
  throw new Error(`Missing skins dir at ${skinsDir}`);
}

/** Keep only html[data-brand] activation — strip global :root / optional .dark binding. */
function toScopedCatalogCss(css, id) {
  const scoped = `html[data-brand="${id}"] {`;
  const out = css
    // darkDefault=true global: ":root,\n.dark,\nhtml[data-brand=\"id\"] {"
    .replace(/:root\s*,\s*\n\.dark\s*,\s*\nhtml\[data-brand="[^"]+"\]\s*\{/g, scoped)
    .replace(/:root\s*,\s*\.dark\s*,\s*html\[data-brand="[^"]+"\]\s*\{/g, scoped)
    // darkDefault=false global: ":root,\nhtml[data-brand=\"id\"] {" (no .dark)
    .replace(/:root\s*,\s*\nhtml\[data-brand="[^"]+"\]\s*\{/g, scoped)
    .replace(/:root\s*,\s*html\[data-brand="[^"]+"\]\s*\{/g, scoped);

  // Safety: never leave a bare :root { color block from a skin
  if (/^:root\s*\{/m.test(out) || /\n:root\s*,/.test(out)) {
    throw new Error(`Skin ${id} still binds :root after scoping — fix emit or regex`);
  }
  return out.trimEnd();
}

const files = readdirSync(skinsDir)
  .filter((f) => f.endsWith(".css") && f !== "README.md")
  .sort();

const ids = [];
const chunks = [
  "/**",
  " * @nebutra/theme — skins.css (design-language catalog)",
  " * AUTO-GENERATED by scripts/sync-skins.mjs — DO NOT EDIT.",
  " *",
  " * Product chrome SSOT: @nebutra/tokens/styles.css + recipe.css",
  " * This file: scoped Brand Package skins under html[data-brand] only.",
  ' * Switch: document.documentElement.dataset.brand = "vanta" | "linear" | ...',
  ' * Factory: delete dataset.brand (or clearLanguage() / applyLanguage("factory")).',
  " *",
  ` * Languages: ${files.map((f) => f.replace(/\.css$/, "")).join(", ")}`,
  " */",
  "",
];

for (const file of files) {
  const id = file.replace(/\.css$/, "");
  const raw = readFileSync(join(skinsDir, file), "utf8");
  ids.push(id);
  chunks.push(toScopedCatalogCss(raw, id));
  chunks.push("");
}

writeFileSync(outPath, `${chunks.join("\n").trimEnd()}\n`);
formatGenerated(outPath);
/**
 * Which typefaces each language asks for, emitted alongside the sheet.
 *
 * A switch has to make the incoming faces resident *before* it starts, or the
 * cross-fade photographs a fallback and the real face swaps in after the
 * animation has finished — a jump landing on a settled page, which is the one
 * people actually see. The switcher needs the list to do that.
 *
 * It is generated here rather than parsed by each consumer: the design site used
 * to read this file off disk at build time, which works exactly once, for an app
 * that happens to sit two directories below the repo root. The package that
 * writes the stylesheet is the only thing that can be sure the list matches it.
 *
 * Generics are dropped — they are always resident and document.fonts.load on
 * them is a wasted round trip. Purely numeric values are dropped too:
 * `--font-weight-*` matches the same prefix and would otherwise ask the browser
 * for a family called "600".
 */
const GENERIC = new Set([
  "ui-sans-serif",
  "ui-serif",
  "ui-monospace",
  "system-ui",
  "sans-serif",
  "serif",
  "monospace",
  "-apple-system",
  "Georgia",
]);

const sheet = readFileSync(outPath, "utf8");
const fonts = {};
for (const block of sheet.matchAll(/html[^{]*\[data-brand="([a-z0-9-]+)"\][^{]*\{([^}]*)\}/g)) {
  const [, brand, body] = block;
  const bucket = (fonts[brand] ??= new Set());
  for (const decl of body.matchAll(/--font-[a-z-]+:\s*([^;]+);/g)) {
    for (const raw of decl[1].split(",")) {
      const family = raw.trim().replace(/^["']|["']$/g, "");
      if (!family || /^\d+$/.test(family) || GENERIC.has(family)) continue;
      bucket.add(family);
    }
  }
}
const fontsPath = join(packageRoot, "src", "skin-fonts.generated.json");
writeFileSync(
  fontsPath,
  `${JSON.stringify(
    Object.fromEntries(Object.entries(fonts).map(([id, set]) => [id, [...set]])),
    null,
    2,
  )}\n`,
);

process.stdout.write(
  `skins.css refreshed: ${ids.length} languages -> ${outPath}\n` +
    `skin-fonts.generated.json: ${Object.keys(fonts).length} languages\n`,
);
