import fs from "node:fs";
import path from "node:path";
import type { AuthChoice } from "./auth.js";
import {
  getSocialLoginProvider,
  SOCIAL_LOGIN_PROVIDERS,
  type SocialLoginId,
  type SocialLoginMeta,
} from "./auth-social.js";

/**
 * Apply China-region social login providers to a scaffolded project.
 *
 * For each selected provider the function will:
 *  1. Append the required env vars to `.env.example`
 *  2. Generate an OAuth callback route stub under
 *     `apps/web/src/app/api/auth/callback/<id>/route.ts`
 *  3. Emit a shared `SocialLoginButtons.tsx` component that renders buttons
 *     only for the selected providers
 *
 * The primary auth provider (Clerk / Better Auth) remains the owner of the
 * user/session lifecycle — these callbacks exchange the OAuth `code` for a
 * provider access token and leave a `// TODO: upsert into primary auth` marker
 * for the user to wire into their chosen stack.
 */

/**
 * Build the body of an OAuth callback `route.ts` for a given provider.
 *
 * The stub is intentionally opinionated but small — it demonstrates the
 * `code` + `state` handling plus the provider-specific token exchange URL, and
 * leaves the "upsert into primary auth" step as an explicit TODO.
 */
function renderCallbackRoute(provider: SocialLoginMeta, primaryAuth: AuthChoice): string {
  const header = `// apps/web/src/app/api/auth/callback/${provider.id}/route.ts
// Generated by create-sailor — OAuth callback for ${provider.name}
// Primary auth provider: ${primaryAuth}
// Docs: ${provider.docs}`;

  // Provider-specific token exchange bodies. Each branch documents the exact
  // query parameters that provider's OAuth endpoint expects.
  const exchangeBlocks: Record<SocialLoginId, string> = {
    wechat: `  const tokenRes = await fetch(
    "${provider.tokenEndpoint}?" +
      new URLSearchParams({
        appid: process.env.WECHAT_APP_ID ?? "",
        secret: process.env.WECHAT_APP_SECRET ?? "",
        code,
        grant_type: "authorization_code",
      }),
  );
  const token = (await tokenRes.json()) as {
    access_token?: string;
    openid?: string;
    errcode?: number;
    errmsg?: string;
  };
  if (!token.access_token || !token.openid) {
    return NextResponse.redirect(new URL("/login?error=wechat_token", req.url));
  }`,
    qq: `  const tokenRes = await fetch(
    "${provider.tokenEndpoint}?" +
      new URLSearchParams({
        client_id: process.env.QQ_APP_ID ?? "",
        client_secret: process.env.QQ_APP_KEY ?? "",
        code,
        grant_type: "authorization_code",
        redirect_uri: new URL("${provider.callbackUrl}", req.url).toString(),
        fmt: "json",
      }),
  );
  const token = (await tokenRes.json()) as { access_token?: string; openid?: string };
  if (!token.access_token) {
    return NextResponse.redirect(new URL("/login?error=qq_token", req.url));
  }`,
    dingtalk: `  const tokenRes = await fetch("${provider.tokenEndpoint}", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      clientId: process.env.DINGTALK_APP_ID ?? "",
      clientSecret: process.env.DINGTALK_APP_SECRET ?? "",
      code,
      grantType: "authorization_code",
    }),
  });
  const token = (await tokenRes.json()) as { accessToken?: string };
  if (!token.accessToken) {
    return NextResponse.redirect(new URL("/login?error=dingtalk_token", req.url));
  }`,
    workweixin: `  // Enterprise WeChat returns an access_token by pairing corpId + secret
  const tokenRes = await fetch(
    "${provider.tokenEndpoint}?" +
      new URLSearchParams({
        corpid: process.env.WORKWEIXIN_CORP_ID ?? "",
        corpsecret: process.env.WORKWEIXIN_SECRET ?? "",
      }),
  );
  const token = (await tokenRes.json()) as {
    access_token?: string;
    errcode?: number;
    errmsg?: string;
  };
  if (!token.access_token) {
    return NextResponse.redirect(new URL("/login?error=workweixin_token", req.url));
  }`,
    feishu: `  // Step 1: app_access_token
  const appTokenRes = await fetch(
    "https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        app_id: process.env.FEISHU_APP_ID ?? "",
        app_secret: process.env.FEISHU_APP_SECRET ?? "",
      }),
    },
  );
  const appToken = (await appTokenRes.json()) as { app_access_token?: string };
  if (!appToken.app_access_token) {
    return NextResponse.redirect(new URL("/login?error=feishu_app_token", req.url));
  }
  // Step 2: user access_token
  const tokenRes = await fetch("${provider.tokenEndpoint}", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${appToken.app_access_token}\`,
    },
    body: JSON.stringify({ grant_type: "authorization_code", code }),
  });
  const token = (await tokenRes.json()) as { data?: { access_token?: string } };
  if (!token.data?.access_token) {
    return NextResponse.redirect(new URL("/login?error=feishu_token", req.url));
  }`,
    weibo: `  const tokenRes = await fetch("${provider.tokenEndpoint}", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: process.env.WEIBO_APP_KEY ?? "",
      client_secret: process.env.WEIBO_APP_SECRET ?? "",
      grant_type: "authorization_code",
      code,
      redirect_uri: new URL("${provider.callbackUrl}", req.url).toString(),
    }),
  });
  const token = (await tokenRes.json()) as { access_token?: string; uid?: string };
  if (!token.access_token) {
    return NextResponse.redirect(new URL("/login?error=weibo_token", req.url));
  }`,
  };

  return `${header}
import { type NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  const code = req.nextUrl.searchParams.get("code");
  const state = req.nextUrl.searchParams.get("state");

  if (!code) {
    return NextResponse.redirect(new URL("/login?error=no_code", req.url));
  }

${exchangeBlocks[provider.id]}

  // TODO: fetch user profile from ${provider.name} using the access token.
  // TODO: upsert the user into your primary auth provider (${primaryAuth}).
  //       e.g. clerk.users.createUser(...) or betterAuth.signIn.oauth(...).
  //       Persist a session cookie before redirecting.

  void state;
  return NextResponse.redirect(new URL("/dashboard", req.url));
}
`;
}

function renderSocialLoginButtons(providers: SocialLoginMeta[]): string {
  const providersLiteral = providers
    .map(
      (p) =>
        `  { id: ${JSON.stringify(p.id)}, name: ${JSON.stringify(p.name)}, href: ${JSON.stringify(`/api/auth/oauth/${p.id}`)} }`,
    )
    .join(",\n");

  return `"use client";

/**
 * SocialLoginButtons — generated by create-sailor.
 *
 * Renders a button per selected China-region OAuth provider. Clicking a
 * button navigates to the provider's authorization URL (\`/api/auth/oauth/<id>\`),
 * which the app is expected to implement and redirect to the upstream consent
 * page. The OAuth callback lives at \`/api/auth/callback/<id>\`.
 */

import { Button } from "@nebutra/ui/components";

interface SocialProvider {
  id: string;
  name: string;
  href: string;
}

const PROVIDERS: SocialProvider[] = [
${providersLiteral},
];

export function SocialLoginButtons() {
  return (
    <div className="space-y-2">
      {PROVIDERS.map((p) => (
        <Button
          key={p.id}
          type="button"
          variant="outline"
          className="w-full"
          onClick={() => {
            window.location.href = p.href;
          }}
        >
          Sign in with {p.name}
        </Button>
      ))}
    </div>
  );
}
`;
}

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function appendEnv(targetDir: string, content: string): void {
  const envExamplePath = path.join(targetDir, ".env.example");
  if (fs.existsSync(envExamplePath)) {
    fs.appendFileSync(envExamplePath, "\n" + content);
  } else {
    fs.writeFileSync(envExamplePath, content);
  }
}

function buildEnvBlock(provider: SocialLoginMeta): string {
  const header = `# ${provider.name} (${provider.id}) — ${provider.docs}`;
  const vars = provider.envVars.map((v) => `${v}=`).join("\n");
  return `${header}\n${vars}\n`;
}

/**
 * Apply the selected social login providers to the scaffolded project.
 *
 * Silent-skip semantics: missing `apps/web` directory causes a no-op so the
 * CLI remains compatible with non-standard monorepo layouts that the caller
 * can wire up manually.
 */
export async function applySocialLoginProviders(
  targetDir: string,
  ids: SocialLoginId[],
  primaryAuth: AuthChoice,
): Promise<void> {
  if (!ids || ids.length === 0) return;

  const webAppDir = path.join(targetDir, "apps", "web");
  if (!fs.existsSync(webAppDir)) return;

  // Dedupe + resolve metadata.
  const seen = new Set<SocialLoginId>();
  const providers: SocialLoginMeta[] = [];
  for (const id of ids) {
    if (seen.has(id)) continue;
    seen.add(id);
    const meta = getSocialLoginProvider(id);
    if (meta) providers.push(meta);
  }
  if (providers.length === 0) return;

  // 1. Append env vars.
  for (const p of providers) {
    appendEnv(targetDir, buildEnvBlock(p));
  }

  // 2. Generate callback routes.
  const callbackBase = path.join(webAppDir, "src", "app", "api", "auth", "callback");
  for (const p of providers) {
    const routeDir = path.join(callbackBase, p.id);
    ensureDir(routeDir);
    const routePath = path.join(routeDir, "route.ts");
    fs.writeFileSync(routePath, renderCallbackRoute(p, primaryAuth));
  }

  // 3. Emit shared component.
  const componentsDir = path.join(webAppDir, "src", "components", "auth");
  ensureDir(componentsDir);
  const componentPath = path.join(componentsDir, "SocialLoginButtons.tsx");
  fs.writeFileSync(componentPath, renderSocialLoginButtons(providers));
}

/** Re-export for convenience. */
export { SOCIAL_LOGIN_PROVIDERS };
