import { brand } from "@nebutra/brand";
import { toMessageLocale } from "@nebutra/i18n/locales";
import { hasLocale } from "next-intl";
import { getRequestConfig } from "next-intl/server";
import { routing } from "./routing";

/**
 * ICU brand-variable map injected into every locale's message catalog at
 * request time. Source of truth: @nebutra/brand/metadata (generated by
 * `pnpm brand:apply` from DEFAULT_BRAND in scripts/brand-types.ts).
 *
 * Placeholder contract:
 *   {brandName}      → brand.name          e.g. "Nebutra"
 *   {brandNameCn}    → brand.nameCn        e.g. "云毓智能"
 *   {companyLegal}   → brand.nameFull      e.g. "无锡云毓智能科技有限公司"
 *   {companyLegalEn} → brand.nameFullEn    e.g. "Wuxi Nebutra Intelligence Technology Co., Ltd."
 *   {productName}    → brand.name + " Sailor"
 */
export const brandVars: Record<string, string> = {
  brandName: brand.name,
  brandNameCn: brand.nameCn,
  companyLegal: brand.nameFull,
  companyLegalEn: brand.nameFullEn,
  productName: `${brand.name} Sailor`,
};

/**
 * Immutably recurse through a message-catalog object and replace every
 * {placeholder} token in string values with the corresponding brand variable.
 *
 * Safe against:
 *   - next-intl rich-text tags (<highlight>…</highlight>) — left untouched
 *   - numeric-keyed cookie objects ({"0": {…}}) — recurses safely
 *   - unknown placeholder tokens — left as-is (no crash)
 */
export function injectBrandVars(
  obj: Record<string, unknown>,
  vars: Record<string, string>,
): Record<string, unknown> {
  const PLACEHOLDER_RE = /\{(\w+)\}/g;
  const result: Record<string, unknown> = {};

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    if (typeof value === "string") {
      result[key] = value.replace(PLACEHOLDER_RE, (match, name) =>
        Object.hasOwn(vars, name) ? vars[name] : match,
      );
    } else if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      result[key] = injectBrandVars(value as Record<string, unknown>, vars);
    } else {
      result[key] = value;
    }
  }

  return result;
}

export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  const locale = hasLocale(routing.locales, requested) ? requested : routing.defaultLocale;

  // Always load English as the base, then merge the target locale on top.
  // This prevents MISSING_MESSAGE crashes during SSG when translations are incomplete.
  const enMessages = (await import("../../messages/en.json")).default;
  const messageLocale = toMessageLocale(locale);
  const localeMessages =
    messageLocale === "en"
      ? enMessages
      : (await import(`../../messages/${messageLocale}.json`)).default;

  const merged = { ...enMessages, ...deepMerge(enMessages, localeMessages) };

  return {
    locale,
    messages: injectBrandVars(merged, brandVars),
  };
});

/** Deep-merge b into a, keeping a's values as fallback for missing keys in b. */
function deepMerge(
  a: Record<string, unknown>,
  b: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...a };
  for (const key of Object.keys(b)) {
    if (
      b[key] !== null &&
      typeof b[key] === "object" &&
      !Array.isArray(b[key]) &&
      typeof a[key] === "object" &&
      a[key] !== null &&
      !Array.isArray(a[key])
    ) {
      result[key] = deepMerge(a[key] as Record<string, unknown>, b[key] as Record<string, unknown>);
    } else {
      result[key] = b[key];
    }
  }
  return result;
}
