/**
 * Global VC directory — a curated set of well-known global investors
 * (accelerators, seed, multi-stage and growth funds) relevant to founders
 * going global. Hand-authored from public information; renders through the
 * same `<VcDirectory>` as the China directory.
 */
import type { VcOrg } from "./vc";

export type { VcOrg } from "./vc";

export const GLOBAL_VC_ORGS: VcOrg[] = [
  {
    id: 1,
    name: "Y Combinator",
    types: ["Accelerator", "Seed"],
    sectors: ["AI", "SaaS", "Fintech", "DevTools", "Consumer"],
    summary:
      "The defining startup accelerator; standardized seed terms and a vast founder network.",
    website: "https://www.ycombinator.com",
    region: "US · SF Bay",
    founded: 2005,
  },
  {
    id: 2,
    name: "Andreessen Horowitz (a16z)",
    types: ["Multi-stage", "Growth", "Crypto"],
    sectors: ["AI", "Crypto", "Bio", "Enterprise", "Consumer"],
    summary: "Multi-stage firm with dedicated funds across AI, crypto, bio and American dynamism.",
    website: "https://a16z.com",
    region: "US · SF Bay",
    founded: 2009,
  },
  {
    id: 3,
    name: "Sequoia Capital",
    types: ["Multi-stage", "Growth"],
    sectors: ["AI", "SaaS", "Fintech", "Consumer", "Enterprise"],
    summary: "Long-running multi-stage firm; backer of many category-defining companies.",
    website: "https://www.sequoiacap.com",
    region: "US · SF Bay",
    founded: 1972,
  },
  {
    id: 4,
    name: "Accel",
    types: ["Early-stage", "Growth"],
    sectors: ["SaaS", "Enterprise", "Fintech", "Consumer"],
    summary: "Early and growth investor across the US, Europe and India.",
    website: "https://www.accel.com",
    region: "Global",
    founded: 1983,
  },
  {
    id: 5,
    name: "Benchmark",
    types: ["Early-stage"],
    sectors: ["Marketplace", "Consumer", "Enterprise", "SaaS"],
    summary: "Small, equal-partnership firm known for high-conviction early bets.",
    website: "https://www.benchmark.com",
    region: "US · SF Bay",
    founded: 1995,
  },
  {
    id: 6,
    name: "Greylock",
    types: ["Early-stage"],
    sectors: ["Enterprise", "AI", "Security", "Consumer"],
    summary: "Seed-to-growth firm with a strong enterprise and AI practice.",
    website: "https://greylock.com",
    region: "US · SF Bay",
    founded: 1965,
  },
  {
    id: 7,
    name: "Kleiner Perkins",
    types: ["Multi-stage"],
    sectors: ["Enterprise", "Consumer", "AI", "Climate"],
    summary: "Storied Sand Hill Road firm investing seed through growth.",
    website: "https://www.kleinerperkins.com",
    region: "US · SF Bay",
    founded: 1972,
  },
  {
    id: 8,
    name: "Founders Fund",
    types: ["Multi-stage"],
    sectors: ["DeepTech", "AI", "Crypto", "Bio", "Enterprise"],
    summary: "Backs ambitious, contrarian technology across stages.",
    website: "https://foundersfund.com",
    region: "US · SF Bay",
    founded: 2005,
  },
  {
    id: 9,
    name: "Lightspeed Venture Partners",
    types: ["Multi-stage", "Growth"],
    sectors: ["Enterprise", "Consumer", "Fintech", "Crypto"],
    summary: "Global multi-stage firm investing across enterprise and consumer.",
    website: "https://lsvp.com",
    region: "Global",
    founded: 2000,
  },
  {
    id: 10,
    name: "Index Ventures",
    types: ["Multi-stage"],
    sectors: ["SaaS", "Fintech", "AI", "Gaming"],
    summary: "Transatlantic firm investing across Europe and the US.",
    website: "https://www.indexventures.com",
    region: "Europe / US",
    founded: 1996,
  },
  {
    id: 11,
    name: "Bessemer Venture Partners",
    types: ["Multi-stage"],
    sectors: ["SaaS", "Cloud", "Healthcare", "Fintech"],
    summary: "One of the oldest VC firms; deep cloud and SaaS practice.",
    website: "https://www.bvp.com",
    region: "US",
    founded: 1911,
  },
  {
    id: 12,
    name: "GV (Google Ventures)",
    types: ["Multi-stage"],
    sectors: ["AI", "Bio", "Enterprise", "Consumer"],
    summary: "Alphabet's venture arm investing across life sciences and tech.",
    website: "https://www.gv.com",
    region: "US",
    founded: 2009,
  },
  {
    id: 13,
    name: "Khosla Ventures",
    types: ["Early-stage", "Multi-stage"],
    sectors: ["DeepTech", "AI", "Climate", "Bio"],
    summary: "Backs bold deep-tech and breakthrough science bets.",
    website: "https://www.khoslaventures.com",
    region: "US · SF Bay",
    founded: 2004,
  },
  {
    id: 14,
    name: "New Enterprise Associates (NEA)",
    types: ["Multi-stage"],
    sectors: ["Enterprise", "Healthcare", "Consumer", "AI"],
    summary: "Large multi-stage firm across technology and healthcare.",
    website: "https://www.nea.com",
    region: "US",
    founded: 1977,
  },
  {
    id: 15,
    name: "General Catalyst",
    types: ["Multi-stage", "Growth"],
    sectors: ["AI", "Healthcare", "Fintech", "Enterprise"],
    summary: "Seed-to-growth firm with a large health-assurance practice.",
    website: "https://www.generalcatalyst.com",
    region: "Global",
    founded: 2000,
  },
  {
    id: 16,
    name: "Tiger Global",
    types: ["Growth"],
    sectors: ["SaaS", "Fintech", "Consumer", "Enterprise"],
    summary: "Crossover firm investing in late-stage private and public tech.",
    website: "https://www.tigerglobal.com",
    region: "US · NYC",
    founded: 2001,
  },
  {
    id: 17,
    name: "Coatue",
    types: ["Growth"],
    sectors: ["AI", "SaaS", "Fintech", "Consumer"],
    summary: "Technology-focused crossover investor across private and public.",
    website: "https://www.coatue.com",
    region: "US · NYC",
    founded: 1999,
  },
  {
    id: 18,
    name: "Insight Partners",
    types: ["Growth"],
    sectors: ["SaaS", "Enterprise", "Fintech", "Security"],
    summary: "Scale-up software investor with a hands-on operations team.",
    website: "https://www.insightpartners.com",
    region: "US · NYC",
    founded: 1995,
  },
  {
    id: 19,
    name: "Thrive Capital",
    types: ["Multi-stage"],
    sectors: ["AI", "Fintech", "Consumer", "Enterprise"],
    summary: "New York firm investing seed through growth in internet and software.",
    website: "https://thrivecap.com",
    region: "US · NYC",
    founded: 2010,
  },
  {
    id: 20,
    name: "First Round Capital",
    types: ["Seed"],
    sectors: ["SaaS", "Consumer", "Fintech", "Enterprise"],
    summary: "Seed-stage specialist with a strong founder community.",
    website: "https://firstround.com",
    region: "US · SF Bay",
    founded: 2004,
  },
  {
    id: 21,
    name: "Union Square Ventures (USV)",
    types: ["Early-stage"],
    sectors: ["Marketplace", "Fintech", "Crypto", "Climate"],
    summary: "Thesis-driven early-stage firm in networks and protocols.",
    website: "https://www.usv.com",
    region: "US · NYC",
    founded: 2003,
  },
  {
    id: 22,
    name: "Spark Capital",
    types: ["Multi-stage"],
    sectors: ["Consumer", "Fintech", "SaaS", "AI"],
    summary: "Early-to-growth firm across consumer and software.",
    website: "https://www.sparkcapital.com",
    region: "US · Boston",
    founded: 2005,
  },
  {
    id: 23,
    name: "Battery Ventures",
    types: ["Multi-stage"],
    sectors: ["Enterprise", "SaaS", "Fintech", "Industrial"],
    summary: "Multi-stage firm spanning software and tech-enabled industries.",
    website: "https://www.battery.com",
    region: "US · Boston",
    founded: 1983,
  },
  {
    id: 24,
    name: "Institutional Venture Partners (IVP)",
    types: ["Growth"],
    sectors: ["SaaS", "Consumer", "Fintech", "AI"],
    summary: "Later-stage firm backing breakout growth companies.",
    website: "https://www.ivp.com",
    region: "US · SF Bay",
    founded: 1980,
  },
  {
    id: 25,
    name: "Redpoint Ventures",
    types: ["Multi-stage"],
    sectors: ["SaaS", "Enterprise", "Fintech", "AI"],
    summary: "Seed-to-growth firm focused on software and infrastructure.",
    website: "https://www.redpoint.com",
    region: "US · SF Bay",
    founded: 1999,
  },
  {
    id: 26,
    name: "Menlo Ventures",
    types: ["Multi-stage"],
    sectors: ["Enterprise", "AI", "Consumer", "Healthcare"],
    summary: "Early-to-growth firm with a dedicated AI fund.",
    website: "https://www.menlovc.com",
    region: "US · SF Bay",
    founded: 1976,
  },
  {
    id: 27,
    name: "Emergence Capital",
    types: ["Early-stage"],
    sectors: ["SaaS", "Enterprise"],
    summary: "Enterprise-SaaS specialist backing cloud application companies.",
    website: "https://www.emcap.com",
    region: "US · SF Bay",
    founded: 2003,
  },
  {
    id: 28,
    name: "Bain Capital Ventures",
    types: ["Multi-stage"],
    sectors: ["Fintech", "SaaS", "Enterprise", "Crypto"],
    summary: "Seed-to-growth arm of Bain Capital across software and fintech.",
    website: "https://baincapitalventures.com",
    region: "US",
    founded: 2001,
  },
  {
    id: 29,
    name: "Lux Capital",
    types: ["Multi-stage"],
    sectors: ["DeepTech", "Bio", "AI", "Hardware"],
    summary: "Backs science and deep-tech at the frontier.",
    website: "https://www.luxcapital.com",
    region: "US · NYC",
    founded: 2000,
  },
  {
    id: 30,
    name: "DCVC (Data Collective)",
    types: ["Early-stage"],
    sectors: ["DeepTech", "AI", "Climate", "Bio"],
    summary: "Deep-tech and computational-science investor.",
    website: "https://www.dcvc.com",
    region: "US · SF Bay",
    founded: 2010,
  },
  {
    id: 31,
    name: "Ribbit Capital",
    types: ["Multi-stage"],
    sectors: ["Fintech", "Crypto", "AI"],
    summary: "Fintech-focused firm investing globally across stages.",
    website: "https://ribbitcap.com",
    region: "US · SF Bay",
    founded: 2012,
  },
  {
    id: 32,
    name: "QED Investors",
    types: ["Multi-stage"],
    sectors: ["Fintech"],
    summary: "Fintech specialist backing companies across the US, LatAm and Europe.",
    website: "https://www.qedinvestors.com",
    region: "Global",
    founded: 2007,
  },
  {
    id: 33,
    name: "Paradigm",
    types: ["Crypto", "Multi-stage"],
    sectors: ["Crypto", "AI"],
    summary: "Crypto-focused firm backing protocols and infrastructure.",
    website: "https://www.paradigm.xyz",
    region: "US · SF Bay",
    founded: 2018,
  },
  {
    id: 34,
    name: "Craft Ventures",
    types: ["Early-stage", "Growth"],
    sectors: ["SaaS", "Marketplace", "Crypto", "Enterprise"],
    summary: "Seed-to-growth firm with a SaaS and marketplaces focus.",
    website: "https://www.craftventures.com",
    region: "US · SF Bay",
    founded: 2017,
  },
  {
    id: 35,
    name: "Felicis",
    types: ["Multi-stage"],
    sectors: ["AI", "SaaS", "Bio", "Fintech"],
    summary: "Multi-stage firm investing across software, AI and health.",
    website: "https://www.felicis.com",
    region: "US · SF Bay",
    founded: 2006,
  },
  {
    id: 36,
    name: "500 Global",
    types: ["Accelerator", "Seed"],
    sectors: ["SaaS", "Fintech", "Consumer"],
    summary: "Global early-stage firm and accelerator across many markets.",
    website: "https://500.co",
    region: "Global",
    founded: 2010,
  },
  {
    id: 37,
    name: "Techstars",
    types: ["Accelerator", "Seed"],
    sectors: ["SaaS", "Fintech", "Consumer", "Enterprise"],
    summary: "Worldwide accelerator network with programs across many cities.",
    website: "https://www.techstars.com",
    region: "Global",
    founded: 2006,
  },
  {
    id: 38,
    name: "Antler",
    types: ["Accelerator", "Seed"],
    sectors: ["SaaS", "Fintech", "AI", "Consumer"],
    summary: "Day-zero venture builder and early-stage investor across continents.",
    website: "https://www.antler.co",
    region: "Global",
    founded: 2017,
  },
  {
    id: 39,
    name: "Atomico",
    types: ["Multi-stage"],
    sectors: ["SaaS", "Fintech", "Consumer", "Climate"],
    summary: "European multi-stage firm founded by a Skype co-founder.",
    website: "https://atomico.com",
    region: "Europe",
    founded: 2006,
  },
  {
    id: 40,
    name: "Balderton Capital",
    types: ["Multi-stage"],
    sectors: ["SaaS", "Fintech", "Consumer"],
    summary: "London-based firm investing across European technology.",
    website: "https://www.balderton.com",
    region: "Europe",
    founded: 2000,
  },
  {
    id: 41,
    name: "Northzone",
    types: ["Multi-stage"],
    sectors: ["Fintech", "SaaS", "Consumer"],
    summary: "European firm backing companies from early stage to growth.",
    website: "https://northzone.com",
    region: "Europe",
    founded: 1996,
  },
  {
    id: 42,
    name: "Creandum",
    types: ["Early-stage"],
    sectors: ["SaaS", "Consumer", "Fintech"],
    summary: "Early-stage European firm; early backer of consumer and SaaS leaders.",
    website: "https://www.creandum.com",
    region: "Europe",
    founded: 2003,
  },
  {
    id: 43,
    name: "DST Global",
    types: ["Growth"],
    sectors: ["Consumer", "Fintech", "SaaS"],
    summary: "Late-stage growth investor in global internet companies.",
    website: "https://dst-global.com",
    region: "Global",
    founded: 2009,
  },
  {
    id: 44,
    name: "SoftBank Vision Fund",
    types: ["Growth"],
    sectors: ["AI", "Consumer", "Fintech", "Enterprise"],
    summary: "Large late-stage growth fund investing in AI-driven companies.",
    website: "https://visionfund.com",
    region: "Global",
    founded: 2017,
  },
];

function uniqueOrdered(values: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const v of values) {
    if (!seen.has(v)) {
      seen.add(v);
      out.push(v);
    }
  }
  return out;
}

export const GLOBAL_VC_COUNT = GLOBAL_VC_ORGS.length;
export const GLOBAL_VC_SECTORS = uniqueOrdered(GLOBAL_VC_ORGS.flatMap((o) => o.sectors)).sort();
export const GLOBAL_VC_TYPES = uniqueOrdered(GLOBAL_VC_ORGS.flatMap((o) => o.types));
export const GLOBAL_VC_REGIONS = uniqueOrdered(
  GLOBAL_VC_ORGS.map((o) => o.region).filter((r): r is string => Boolean(r)),
);

/** Ids with a curated local logo at `/logos/vc-global/<id>.png`. */
export const GLOBAL_VC_LOGO_IDS: ReadonlySet<number> = new Set<number>([
  1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
]);

export function globalVcLogoFor(org: VcOrg): string | null {
  return GLOBAL_VC_LOGO_IDS.has(org.id) ? `/logos/vc-global/${org.id}.png` : null;
}

const GLOBAL_BY_ID = new Map(GLOBAL_VC_ORGS.map((o) => [o.id, o]));
export function getGlobalVc(id: number): VcOrg | undefined {
  return GLOBAL_BY_ID.get(id);
}
